Repository keepassxreboot/keepassxc, pull requests merged in 2018-03, with the labels that each got.

#1607 Do not delete MacPasteboard instance on exit, resolves #1543
  src/core/MacPasteboard.h
  src/gui/Clipboard.cpp
  src/gui/Clipboard.h
Labels: OS-Mac, bug

#1608 Fix regression: basic filename, password and keyfile command line parameters being ignored
  src/main.cpp
Labels: bug

#1609 Resize details widget to minimum by default
  src/gui/DatabaseWidget.cpp
Labels: bug, user interface

#1610 Open previously opened databases in correct order
  src/gui/MainWindow.cpp
Labels: bug, regression

#1587 SSH Agent: Fix handling of encrypted RSA keys
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/sshagent/OpenSSHKey.cpp
  src/sshagent/SSHAgent.cpp
Labels: bug, sshagent

#1613 Avoid conditional use of possibly uninitialized value in CategoryListWidgetDelegate
  src/gui/CategoryListWidget.cpp
Labels: bug

#1612 Fix GCC 8 memset warning and set -Werror only for debug builds
  CMakeLists.txt
  src/http/Server.cpp
Labels: build system

#1641 KdbxReader::readDatabase: abort if reading magic numbers fails
  src/format/KdbxReader.cpp
Labels: file format

#1649 Allow references to be part of a field
  src/core/Entry.cpp
Labels: bug, plugin: Auto-Type

#1651 Add test case for recursive placeholders
  src/core/Entry.cpp
  tests/TestEntry.cpp
Labels: bug, plugin: Reference/Placeholders

#1657 Add User-Agent header and set request timeout to avoid infinite download hangs
  src/gui/EditWidgetIcons.cpp
Labels: bug, plugin: Networking

#1614 SSH Agent: Show error messages if there are problems with agent communication
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: user interface

#1646 KdbxXmlReader: Support Protected attribute on most nodes
  src/format/KdbxXmlReader.cpp
  src/format/KdbxXmlReader.h
Labels: bug, file format

#1640 attributes: unbreak copy-to-clipboard on KDE
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
Labels: bug, platform: KDE

#1628 Fix freeze and high CPU usage on invalid STDIN data
  src/browser/NativeMessagingHost.cpp
  src/main.cpp
  src/proxy/NativeMessagingHost.cpp
Labels: bug, plugin: Browser integration

#1659 Raise error if challenge-response failed during KDBX4 key transformation
  src/keys/CompositeKey.cpp
  src/keys/CompositeKey.h
Labels: bug, security

#1662 Remove qsvg imageformat plugin to prevent crash when trying to load SVG icons
  src/CMakeLists.txt
Labels: bug, distribution, platform: Windows

#1680 Fix dark tray icon option making all icons dark
  src/core/FilePath.cpp
  src/core/FilePath.h
  src/gui/MainWindow.cpp
Labels: bug, user interface

#1686 Change `--pw-stdin` to use `getPassword()`
  src/main.cpp
Labels: plugin: CLI, security

#1691 Fix inconsistent mutex unlocking due to double slot execution
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
Labels: bug, platform: Windows

#1696 Always hide password on unlock
  src/gui/DatabaseOpenWidget.cpp
Labels: security, user interface

#1681 OpenSSHKey: when writing to agent, ensure comment string is at least one byte
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/SSHAgent.cpp
Labels: plugin: SSH agent

#1679 SSH Agent: Update available attachments immediately
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
Labels: new feature, plugin: SSH agent

#1677 SSH Agent: Helpful error message for adding keys
  src/sshagent/SSHAgent.cpp
Labels: new feature, plugin: SSH agent

#1665 Fix extension URL
  README.md
Labels: documentation, needs rebase

#1719 Fix wrong reply size in NativeMessagingBase
  src/browser/NativeMessagingBase.cpp
Labels: bug, plugin: Browser integration

#1747 Enable high entropy ASLR for Windows builds
  CMakeLists.txt
Labels: platform: Windows, security

#1725 Improve translation base strings
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserService.cpp
  src/core/CsvParser.cpp
  src/core/Database.cpp
  src/core/Entry.cpp
  src/core/Group.cpp
  src/format/Kdbx3Reader.cpp
  src/format/KdbxXmlReader.cpp
  src/format/KeePass1Reader.cpp
  src/gui/AboutDialog.cpp
  src/gui/ChangeMasterKeyWidget.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseRepairWidget.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/DetailsWidget.cpp
  src/gui/EditWidgetIcons.cpp
  src/gui/MainWindow.cpp
  src/gui/SearchWidget.cpp
  src/gui/TotpDialog.cpp
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/csvImport/CsvParserModel.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.cpp
Labels: i18n

#1749 Docs
  INSTALL.md
Labels: documentation

#1722 Do not ignore MainWindow closeEvent when closing to tray
  src/gui/MainWindow.cpp
Labels: bug, high priority

#1702 Grey out Apply button when there are no changes
  src/gui/EditWidget.cpp
  src/gui/EditWidget.h
  src/gui/EditWidgetIcons.cpp
  src/gui/EditWidgetIcons.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EntryAttachmentsWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.h
  tests/gui/TestGui.cpp
Labels: user interface
