Repository keepassxreboot/keepassxc, pull requests merged in 2018-10, with the labels that each got.

#2332 Fix TouchID compiling with macOS
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
Labels: platform: macOS

#2345 Add option to list elements recursively in the cli
  src/cli/List.cpp
  src/cli/List.h
Labels: new feature, plugin: CLI

#2253 Fix checking subdomains
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: PR: Ready for Merge, bug, plugin: Browser integration, regression

#1167 QR Code generator
  CMakeLists.txt
  Dockerfile
  ci/trusty/Dockerfile
  cmake/FindQREncode.cmake
  snapcraft.yaml
  src/CMakeLists.txt
  src/core/Entry.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/SquareSvgWidget.cpp
  src/gui/SquareSvgWidget.h
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/TotpExportSettingsDialog.h
  src/qrcode/CMakeLists.txt
  src/qrcode/QrCode.cpp
  src/qrcode/QrCode.h
  src/qrcode/QrCode_p.h
  src/totp/totp.cpp
  src/totp/totp.h
Labels: PR: Ready for Merge, new feature, user interface

#2402 Multiple fixes to MainWindow and some cleanup
  snapcraft.yaml
  src/core/Bootstrap.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug, ux

#2404 Enable high-DPI scaling to support 4k screens
  src/gui/KMessageWidget.cpp
  src/main.cpp
Labels: bug, high-dpi

#2396 Show a warning message when native messaging host is not found
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/HostInstaller.cpp
  src/browser/HostInstaller.h
Labels: plugin: Browser integration

#2411 Remove macro that caused Qt Creator to error out
  src/crypto/kdf/AesKdf.h
  src/crypto/kdf/Argon2Kdf.h
  src/keys/CompositeKey.h
Labels: build system

#2384 Convert preview panel close button from checkbox to momentary
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
Labels: bug, user interface

#2382 Make preview panel expiration date use local time
  src/gui/EntryPreviewWidget.cpp
Labels: i18n, user interface

#1497 Use custom data to save any browser integration related data
  src/CMakeLists.txt
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserEntryConfig.cpp
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.h
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/browser/NativeMessagingHost.cpp
  src/browser/NativeMessagingHost.h
  src/gui/MainWindow.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.h
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.h
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.ui
Labels: PR: Needs Work, new feature, plugin: Browser integration

#2419 Replace deprecated parts of code
  src/autotype/AutoType.cpp
  src/autotype/AutoTypePlatformPlugin.h
  src/autotype/AutoTypeSelectDialog.cpp
  src/autotype/test/AutoTypeTest.cpp
  src/autotype/test/AutoTypeTest.h
  src/browser/HostInstaller.cpp
  src/browser/NativeMessagingBase.cpp
  src/core/Bootstrap.cpp
  src/core/Config.cpp
  src/core/FilePath.cpp
  src/core/Metadata.cpp
  src/core/ScreenLockListenerPrivate.cpp
  src/gui/Application.cpp
  src/gui/Clipboard.cpp
  src/gui/Clipboard.h
  src/gui/DatabaseWidget.cpp
  src/gui/DialogyWidget.cpp
  src/gui/FileDialog.cpp
  src/gui/KMessageWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/csvImport/CsvImportWidget.h
  src/gui/entry/AutoTypeMatchView.cpp
  src/gui/entry/EntryView.cpp
  src/main.cpp
Labels: PR: Ready for Merge

#2425 Fix stdin/stdout encoding on Windows.
  src/CMakeLists.txt
  src/cli/Add.cpp
  src/cli/Clip.cpp
  src/cli/Diceware.cpp
  src/cli/Edit.cpp
  src/cli/Estimate.cpp
  src/cli/Extract.cpp
  src/cli/Generate.cpp
  src/cli/List.cpp
  src/cli/Locate.cpp
  src/cli/Merge.cpp
  src/cli/Remove.cpp
  src/cli/Show.cpp
  src/cli/TextStream.cpp
  src/cli/TextStream.h
  src/cli/Utils.cpp
  src/cli/Utils.h
  src/cli/keepassxc-cli.cpp
  tests/TestCli.cpp
Labels: bug, platform: Windows, plugin: CLI

#2410 Fix issues with group functions
  src/cli/Clip.cpp
  src/cli/Show.cpp
  src/core/Group.cpp
  src/core/Group.h
  tests/TestGroup.cpp
  tests/TestMerge.cpp
Labels: bug, refactor

#2422 Extract the OS event filter implementation
  src/CMakeLists.txt
  src/core/OSEventFilter.cpp
  src/core/OSEventFilter.h
  src/core/ScreenLockListenerDBus.h
  src/gui/Application.cpp
  src/gui/Application.h
Labels: PR: Ready for Merge, refactor

#2353 Don't obscure password field after invalid password attempt if setting is off
  src/gui/DatabaseOpenWidget.cpp
  src/gui/PasswordEdit.cpp
  src/gui/PasswordEdit.h
Labels: PR: Ready for Merge, user interface

#2387 Added Linux, MacOS support for Tor Browser.
  docs/QUICKSTART.md
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/HostInstaller.cpp
  src/browser/HostInstaller.h
Labels: PR: Ready for Merge, plugin: Browser integration

#2430 Add more expiration presets
  src/gui/entry/EditEntryWidget.cpp
Labels: user interface
