Repository keepassxreboot/keepassxc, pull requests merged in 2018-08, with the labels that each got.

#2185 Allows a separate ID key for browser extension association
  src/browser/BrowserAction.cpp
Labels: bug, plugin: Browser integration

#2173 allow 12 hour timeout for lockDatabaseIdle
  src/gui/SettingsWidgetSecurity.ui
Labels: user interface

#2142 Fix keepassxc-proxy shutdown with Chromium-based browsers under Windows
  src/browser/NativeMessagingBase.h
  src/browser/NativeMessagingHost.cpp
  src/browser/NativeMessagingHost.h
  src/proxy/NativeMessagingHost.cpp
  src/proxy/NativeMessagingHost.h
Labels: platform: Windows, plugin: Browser integration

#2159 Add browser extension links to settings page
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
Labels: plugin: Browser integration

#2211 Provide warning to users with Qt 5.5.x about potential crash
  src/gui/MainWindow.cpp
Labels: documentation

#2214 Enhancements to About dialog and add settings button to toolbar
  share/about-contributors.html
  share/about.html
  src/gui/AboutDialog.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/SearchWidget.ui
Labels: user interface

#2229 Fix --snapcraft flag
  release-tool
Labels: bug, build system

#1969 Prevent Klipper from storing secrets in clipboard history
  src/gui/Clipboard.cpp
  src/gui/Clipboard.h
Labels: new feature
