Repository keepassxreboot/keepassxc, pull requests merged in 2018-11, with the labels that each got.

#2465 Better error message for invalid db file
  src/core/Database.cpp
Labels: plugin: CLI

#2464 Document list -R option.
  src/cli/List.cpp
  src/cli/keepassxc-cli.1
Labels: documentation, plugin: CLI

#2463 Fix compilation without YubiKey
  src/CMakeLists.txt
Labels: bug, regression

#2456 Updating man page authorship
  src/cli/keepassxc-cli.1
Labels: documentation, plugin: CLI

#2444 Fix KeePassHTTP settings to custom data conversion
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, plugin: Browser integration

#2454 CLI: add commands to show and copy TOTP to clipboard
  src/cli/Clip.cpp
  src/cli/Clip.h
  src/cli/Show.cpp
  src/cli/Show.h
  src/cli/keepassxc-cli.1
  tests/TestCli.cpp
  tests/TestCli.h
  tests/data/NewDatabase.kdbx
  tests/data/NewDatabase2.kdbx
  tests/gui/TestGui.cpp
Labels: PR: Ready for Merge, plugin: CLI

#2466 CLI Merge: Only save database file when modified.
  src/cli/Merge.cpp
  tests/TestCli.cpp
Labels: plugin: CLI

#2431 Fix multiple issues with entry keyboard shortcuts
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  src/gui/EntryPreviewWidget.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/SearchWidget.cpp
  src/gui/SearchWidget.ui
  src/gui/entry/EntryModel.cpp
  src/gui/entry/EntryModel.h
  src/gui/entry/EntryView.cpp
  src/gui/entry/EntryView.h
  tests/gui/TestGui.cpp
Labels: ux

#2503 Fix bugs introduced by database refactor #2491
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/PasswordEdit.cpp
  src/gui/PasswordEdit.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: bug, high priority

#2506 Refactor DatabaseOpenWidget/Dialog and Auto-Type Database unlocking
  src/CMakeLists.txt
  src/gui/DatabaseOpenDialog.cpp
  src/gui/DatabaseOpenDialog.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/KeePass1OpenWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/UnlockDatabaseDialog.cpp
  src/gui/UnlockDatabaseWidget.cpp
  src/gui/UnlockDatabaseWidget.h
  tests/gui/TestGui.cpp
Labels: refactor

#2439 Add favicon fetch button next to entry's url edit textbox
  COPYING
  share/icons/application/16x16/actions/favicon-download.png
  share/icons/application/22x22/actions/favicon-download.png
  share/icons/application/32x32/actions/favicon-download.png
  src/gui/EditWidgetIcons.cpp
  src/gui/EditWidgetIcons.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EditEntryWidgetMain.ui
Labels: PR: Ready for Merge, ux

#2479 Update Github templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2518 Correct refactor issues with entry selection and search
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/entry/EntryView.cpp
  src/gui/entry/EntryView.h
  src/gui/group/GroupView.cpp
  src/gui/group/GroupView.h
  tests/gui/TestGui.cpp
Labels: bug

#2437 Correct simultaneous saving with Yubikey
  src/keys/YkChallengeResponseKey.cpp
  src/keys/YkChallengeResponseKey.h
  src/keys/drivers/YubiKey.cpp
  src/keys/drivers/YubiKey.h
Labels: PR: Ready for Merge, bug, high priority

#2505 Global const for KeyFileOption (CLI)
  src/cli/Add.cpp
  src/cli/Clip.cpp
  src/cli/Command.cpp
  src/cli/Command.h
  src/cli/Edit.cpp
  src/cli/Extract.cpp
  src/cli/List.cpp
  src/cli/Locate.cpp
  src/cli/Merge.cpp
  src/cli/Remove.cpp
  src/cli/Show.cpp
Labels: PR: Ready for Merge, plugin: CLI, refactor
