Repository keepassxreboot/keepassxc, pull requests merged in 2019-01, with the labels that each got.

#2580 Fix macOS makefiles for cli and proxy
  src/cli/CMakeLists.txt
  src/proxy/CMakeLists.txt
Labels: PR: Ready for Merge, platform: macOS

#2584 Edit entry widget: password generator: fix flicker
  src/gui/entry/EditEntryWidget.cpp
Labels: PR: Ready for Merge

#2583 Fix native hiding of macOS windows
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/macutils/AppKit.h
  src/gui/macutils/AppKitImpl.h
  src/gui/macutils/AppKitImpl.mm
  src/gui/macutils/MacUtils.cpp
  src/gui/macutils/MacUtils.h
Labels: PR: Ready for Merge, bug, platform: macOS

#2357 Toolbar and tool buttons style.
  src/core/Config.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/MainWindow.cpp
Labels: PR: Ready for Merge, accessibility, user interface

#2558 We should output to stderr on EXIT_FAILURE
  src/cli/Add.cpp
  src/cli/Clip.cpp
  src/cli/Diceware.cpp
  src/cli/Edit.cpp
  src/cli/Estimate.cpp
  src/cli/Extract.cpp
  src/cli/Generate.cpp
  src/cli/List.cpp
  src/cli/Locate.cpp
  src/cli/Merge.cpp
  src/cli/Remove.cpp
  src/cli/Show.cpp
Labels: PR: Ready for Merge, plugin: CLI

#2576 Prevent post-compilation Qt downgrades
  src/core/Tools.h
  src/gui/MainWindow.cpp
  src/main.cpp
Labels: PR: Ready for Merge

#2622 Clearer default error messages
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
Labels: PR: Ready for Merge, plugin: Browser integration

#2601 Fix crash when canceling save of new database
  src/core/Config.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  tests/gui/TestGui.cpp
Labels: bug, high priority

#2635 Prevent use of wayland theme on Linux
  src/main.cpp
Labels: platform: Linux, user interface

#2596 Allow for KDF seeds between 8 and 32 bytes
  src/crypto/kdf/Kdf.cpp
  src/crypto/kdf/Kdf.h
Labels: file format

#1802 Update README after KeePassHTTP deprecation.
  README.md
Labels: documentation

#2648 Update checking feature
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/UpdateCheckDialog.cpp
  src/gui/UpdateCheckDialog.h
  src/gui/UpdateCheckDialog.ui
  src/updatecheck/UpdateChecker.cpp
  src/updatecheck/UpdateChecker.h
  tests/CMakeLists.txt
  tests/TestUpdateCheck.cpp
  tests/TestUpdateCheck.h
  tests/gui/TestGui.cpp
Labels: distribution, new feature, plugin: Networking, user interface

#2637 Select group when adding credentials from browser extension
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/core/Group.cpp
  src/core/Group.h
  src/core/Tools.cpp
  src/core/Tools.h
  tests/TestGroup.cpp
  tests/TestGroup.h
Labels: PR: Ready for Merge, plugin: Browser integration

#2659 Cleanup CMakeFiles and revert Dockerfile changes
  CMakeLists.txt
  Dockerfile
  cmake/GenerateProductVersion.cmake
  cmake/GetGitRevisionDescription.cmake
  cmake/GetGitRevisionDescription.cmake.in
  release-tool
  src/CMakeLists.txt
  src/browser/BrowserAction.cpp
  src/git-info.h.cmake
  src/gui/AboutDialog.cpp
  src/gui/CloneDialog.cpp
  src/gui/MainWindow.cpp
  src/version.h.cmake
Labels: build system
