Repository keepassxreboot/keepassxc, pull requests merged in 2019-10, with the labels that each got.

#3596 Add hyperlinks to EntryPreviewWidget notes field
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  src/gui/EntryPreviewWidget.ui
Labels: user interface

#3576 Bring window to front on Mac when clicking the system tray
  src/gui/MainWindow.cpp
Labels: bug, platform: macOS

#3603 Fix setting and removing registy values for Browser Integration
  src/browser/HostInstaller.cpp
Labels: platform: Windows, plugin: Browser integration

#3444 Add support for entry related settings with Browser Integration
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EditEntryWidgetBrowser.ui
Labels: PR: Needs Work, plugin: Browser integration

#3610 Fix stylesheet warnings introduced by 3b330ee2
  src/gui/PasswordEdit.cpp
Labels: bug, regression

#3546 Statistics panel in Database Settings dialog
  CHANGELOG.md
  COPYING
  share/icons/application/32x32/actions/statistics.png
  src/CMakeLists.txt
  src/core/Bootstrap.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/dbsettings/DatabaseSettingsPageStatistics.cpp
  src/gui/dbsettings/DatabaseSettingsPageStatistics.h
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.h
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.ui
Labels: bounty :moneybag:, new feature, user interface

#3624 Request screen reader permission for AutoType
  share/macosx/keepassxc.entitlements
  src/cli/CMakeLists.txt
  src/gui/macutils/AppKitImpl.mm
Labels: bug, high priority :rotating_light:, platform: macOS

#3558 Add support for multiple URL's in entry
  src/CMakeLists.txt
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/core/Bootstrap.cpp
  src/core/Entry.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EditEntryWidgetBrowser.ui
  src/gui/entry/EntryURLModel.cpp
  src/gui/entry/EntryURLModel.h
  tests/CMakeLists.txt
  tests/TestBrowser.cpp
  tests/TestBrowser.h
  tests/TestCli.cpp
  tests/TestEntry.cpp
  tests/gui/TestGuiBrowser.cpp
  tests/gui/TestGuiBrowser.h
Labels: bounty :moneybag:, new feature, plugin: Browser integration

#3634 Make macOS Auto-Type more robust
  src/autotype/AutoType.cpp
Labels: bug, platform: macOS, plugin: Auto-Type

#3622 TOTP Setup Fixes
  src/core/Entry.cpp
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/TotpSetupDialog.cpp
  src/gui/TotpSetupDialog.ui
  src/gui/entry/EditEntryWidget.cpp
  src/totp/totp.cpp
  src/totp/totp.h
  tests/TestTotp.cpp
Labels: bug, plugin: TOTP

#3625 Ask user before allowing kdbx files as key files
  src/gui/dbsettings/DatabaseSettingsWidget.cpp
  src/gui/dbsettings/DatabaseSettingsWidget.h
  src/gui/masterkey/KeyFileEditWidget.cpp
  src/gui/masterkey/KeyFileEditWidget.h
  src/gui/masterkey/KeyFileEditWidget.ui
Labels: ux

#3613 Ask to delete recycle bin when disabled in database settings
  src/core/Database.cpp
  src/core/Group.cpp
  src/core/Group.h
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.cpp
  tests/TestGroup.cpp
Labels: bug

#3649 Fix unused variable error when building without WITH_XC_YUBIKEY.
  src/cli/Utils.cpp
Labels: bug

#3653 Update copyright year to 2019
  COPYING
Labels: documentation :bookmark_tabs:

#3639 Browser access control dialog shows submitUrl when found
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, plugin: Browser integration

#3638 Show database name when doing association
  src/browser/BrowserService.cpp
Labels: bug, plugin: Browser integration

#3617 Update QUICKSTART.md
  docs/QUICKSTART.md
Labels: documentation :bookmark_tabs:

#3656 Prevent new entry loss on database file reload
  src/core/Group.cpp
  src/core/Group.h
  src/gui/DatabaseWidget.cpp
Labels: bug, high priority :rotating_light:

#3660 Fix zxcvbn include for out-of-tree compilation, resolves #3658
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.cpp
Labels: bug

#3662 Fix building on Mac OS X 10.11 or older
  src/core/Alloc.cpp
  src/keeshare/ShareExport.cpp
Labels: platform: macOS

#3665 Add keepassxc man page and move cli man page to share folder
  README.md
  share/docs/man/keepassxc-cli.1
  share/docs/man/keepassxc.1
  src/CMakeLists.txt
  src/cli/CMakeLists.txt
Labels: documentation :bookmark_tabs:, platform: Linux, platform: macOS

#3666 Force app exit if session manager signals a shutdown.
  src/core/OSEventFilter.cpp
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug

#3669 Update About Dialog contributors and translators
  src/gui/AboutDialog.cpp
  utils/transifex_translators.py
Labels: documentation :bookmark_tabs:

#3671 Additional fixes for entry context menu
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: regression

#3672 Reduce default Argon2 memory and thread settings
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
Labels: bug

#3693 Fix building without features
  src/keys/drivers/YubiKeyStub.cpp
  tests/CMakeLists.txt
  tests/TestCli.cpp
  tests/gui/CMakeLists.txt
Labels: regression

#3724 Significantly reduce impact of FileWatcher hashing
  src/core/Database.cpp
  src/core/FileWatcher.cpp
  src/core/FileWatcher.h
Labels: bug, high priority :rotating_light:
