Repository keepassxreboot/keepassxc, pull requests merged in 2019-02, with the labels that each got.

#2670 Fix group signals
  src/core/Group.cpp
  tests/TestGroup.cpp
  tests/TestGroup.h
Labels: PRE-RELEASE BUG

#2698 Refactoring database extraction
  src/cli/Extract.cpp
  src/core/Database.cpp
  src/core/Database.h
  src/format/Kdbx3Writer.cpp
  src/format/Kdbx3Writer.h
  src/format/Kdbx4Writer.cpp
  src/format/Kdbx4Writer.h
  src/format/KdbxReader.cpp
  src/format/KdbxReader.h
  src/format/KdbxWriter.cpp
  src/format/KdbxWriter.h
  src/format/KeePass2Reader.cpp
  src/format/KeePass2Reader.h
  src/format/KeePass2Writer.cpp
  src/format/KeePass2Writer.h
Labels: plugin: CLI, refactor

#2683 Updated contributors in about dialog
  .gitignore
  share/about-contributors.html
  share/about.html
  src/gui/AboutDialog.cpp
  src/gui/AboutDialog.ui
Labels: documentation

#2695 Fix quiet option for Merge (CLI)
  src/cli/Merge.cpp
  tests/TestCli.cpp
Labels: bug, plugin: CLI

#2709 Code quality updates for 2.4.0
  src/browser/NativeMessagingBase.h
  src/browser/NativeMessagingHost.h
  src/core/Entry.cpp
  src/core/OSEventFilter.cpp
  src/core/OSEventFilter.h
  src/crypto/kdf/Kdf.cpp
  src/crypto/ssh/BinaryStream.cpp
  src/crypto/ssh/BinaryStream.h
  src/gui/MainWindow.cpp
  src/keeshare/ShareObserver.cpp
  src/proxy/NativeMessagingHost.cpp
  src/proxy/NativeMessagingHost.h
  src/proxy/keepassxc-proxy.cpp
  src/streams/SymmetricCipherStream.cpp
  src/updatecheck/UpdateChecker.cpp
Labels: bug, platform: Windows

#2711 Prevent unnecessary key transformations, resolves #2704
  src/core/Database.cpp
  src/core/Database.h
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
Labels: bug

#2723 fix(NativeMessagingBase): always close epoll/kqueue file descriptor
  src/browser/NativeMessagingBase.cpp
Labels: plugin: Browser integration
