Repository keepassxreboot/keepassxc, pull requests merged in 2019-05, with the labels that each got.

#3093 Close popups when database is locked
  src/browser/BrowserService.cpp
Labels: bug, high priority :rotating_light:, plugin: Browser integration

#3088 Fix QuaZip find module on macOS and clean up code.
  cmake/FindQuaZip.cmake
  src/keeshare/ShareObserver.cpp
Labels: build system, platform: macOS

#3002 Support Database Custom Data Merging
  src/core/CustomData.cpp
  src/core/CustomData.h
  src/core/Merger.cpp
  tests/TestKdbx4.cpp
  tests/TestMerge.cpp
  tests/TestMerge.h
Labels: bug, high priority :rotating_light:, plugin: Browser integration, regression

#3097 Lock database on switching user in macOS
  src/CMakeLists.txt
  src/gui/DatabaseTabWidget.cpp
  src/gui/macutils/AppKit.h
  src/gui/macutils/AppKitImpl.h
  src/gui/macutils/AppKitImpl.mm
  src/gui/macutils/MacUtils.cpp
  src/gui/macutils/MacUtils.h
Labels: bug, high priority :rotating_light:, platform: macOS, security

#3112 Robust processing of tray icon triggers
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  tests/gui/TestGui.cpp
Labels: bug, ux

#3074 Update INSTALL.md and cleanup CMakeLists.txt
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
  src/keeshare/CMakeLists.txt
Labels: build system, documentation :bookmark_tabs:

#3134 Add option for returning expired credentials
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserService.cpp
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
Labels: plugin: Browser integration

#3138 Fix global Auto-Type when database locked
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
  src/autotype/mac/CMakeLists.txt
  src/autotype/test/AutoTypeTest.cpp
  src/autotype/test/AutoTypeTest.h
  src/autotype/test/AutoTypeTestInterface.h
  src/gui/DatabaseTabWidget.cpp
  tests/TestAutoType.cpp
Labels: bug, plugin: Auto-Type

#3153 Fix opening url's with non-http schemes
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
Labels: bug

#3127 Don't create default browser group
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, plugin: Browser integration

#3172 Add word case option to passphrase generator
  src/browser/BrowserSettings.cpp
  src/cli/Diceware.cpp
  src/core/PassphraseGenerator.cpp
  src/core/PassphraseGenerator.h
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.ui
  tests/CMakeLists.txt
  tests/TestPassphraseGenerator.cpp
  tests/TestPassphraseGenerator.h
Labels: new feature

#3180 Read all database attachments even if duplicated
  src/format/Kdbx4Reader.cpp
  src/format/Kdbx4Reader.h
Labels: bug, high priority :rotating_light:

#3016 Browser Integration tests
  src/browser/BrowserAction.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  tests/CMakeLists.txt
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: plugin: Browser integration, tests

#3131 Use Snap-Specific directories
  src/browser/NativeMessagingBase.cpp
  src/gui/entry/EntryAttachmentsWidget.cpp
Labels: distribution: Snap
