Repository keepassxreboot/keepassxc, pull requests merged in 2019-06, with the labels that each got.

#3215 Add documentation for keyboard shortcuts
  INSTALL.md
  README.md
  docs/KEYBINDS.md
Labels: documentation :bookmark_tabs:

#3236 Settings option to shush success KeeShare notifications
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/keeshare/ShareObserver.cpp
Labels: plugin: KeeShare

#3249 Compile with Compiler Cache (ccache) if it's installed
  CMakeLists.txt
Labels: build system

#3244 Add system tray icon for "Toggle Window"
  COPYING
  share/icons/application/16x16/actions/database-lock.png
  share/icons/application/22x22/actions/database-lock.png
  share/icons/application/32x32/actions/database-lock.png
  src/gui/MainWindow.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
Labels: user interface

#3247 Fix issues with 2.4.2 deployment
  snap/snapcraft.yaml
  src/proxy/CMakeLists.txt
Labels: distribution: Snap, high priority :rotating_light:, platform: macOS

#3248 Fix remaining issues with menu keyboard navigation
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/SearchWidget.cpp
Labels: accessibility, bug

#3258 Fix clicking tray icon to toggle window on Linux
  src/gui/MainWindow.cpp
Labels: platform: Linux

#3265 revised this resp. these two guides
  docs/QUICKSTART.md
Labels: documentation :bookmark_tabs:

#3262 Support returning a message for canceled operation
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: new feature, plugin: Browser integration

#3283 Embed version information in AppImage
  release-tool
Labels: distribution: AppImage

#3276 CLI: Add 'flatten' option to the 'ls' command
  CHANGELOG
  src/cli/List.cpp
  src/cli/List.h
  src/cli/keepassxc-cli.1
  src/core/Group.cpp
  src/core/Group.h
  tests/TestCli.cpp
  tests/TestGroup.cpp
  tests/TestGroup.h
  tests/data/NewDatabase.kdbx
Labels: plugin: CLI

#3132 simplify wording of enabling browser integration
  src/browser/BrowserOptionDialog.ui
Labels: user interface

#3254 Add CLI --dry-run option for merge
  src/cli/Merge.cpp
  src/cli/Merge.h
  src/cli/keepassxc-cli.1
  src/core/Merger.cpp
  src/core/Merger.h
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
  src/keeshare/ShareObserver.cpp
  tests/TestCli.cpp
Labels: plugin: CLI

#3273 Allow setting group icons to children groups/entries
  src/core/Group.cpp
  src/core/Group.h
  src/fdosecrets/objects/Collection.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/EditWidgetIcons.cpp
  src/gui/EditWidgetIcons.h
  src/gui/EditWidgetIcons.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/group/EditGroupWidget.cpp
  tests/TestGroup.cpp
  tests/TestGroup.h
Labels: ux

#3038 Add copy context-menu in AutoType dialog
  src/autotype/AutoTypeSelectDialog.cpp
  src/gui/entry/AutoTypeMatchView.cpp
  src/gui/entry/AutoTypeMatchView.h
Labels: plugin: Auto-Type, ux

#3107 Fix keepassxc-browser password entropy display
  src/browser/BrowserAction.cpp
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/core/PassphraseGenerator.cpp
  src/core/PassphraseGenerator.h
  src/core/PasswordGenerator.cpp
  src/core/PasswordGenerator.h
  src/gui/PasswordGeneratorWidget.cpp
Labels: bug, plugin: Browser integration

#3281 Fix resolving placeholders in urls
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.cpp
Labels: bug

#3031 Enforce ShareObserver to resolve relative paths
  src/keeshare/ShareObserver.cpp
  src/keeshare/ShareObserver.h
Labels: plugin: KeeShare

#3029 KeeShare - improve share observer code
  src/keeshare/CMakeLists.txt
  src/keeshare/KeeShare.cpp
  src/keeshare/KeeShare.h
  src/keeshare/ShareExport.cpp
  src/keeshare/ShareExport.h
  src/keeshare/ShareImport.cpp
  src/keeshare/ShareImport.h
  src/keeshare/ShareObserver.cpp
  src/keeshare/ShareObserver.h
Labels: plugin: KeeShare, refactor

#3304 Unbreak build on FreeBSD
  cmake/GNUInstallDirs.cmake
  src/browser/HostInstaller.cpp
  src/core/Alloc.cpp
Labels: build system

#3291 KeeShare settings fixes
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/keeshare/SettingsWidgetKeeShare.cpp
  src/keeshare/SettingsWidgetKeeShare.ui
  src/keeshare/ShareObserver.cpp
Labels: plugin: KeeShare

#3287 Redesign database unlock widget
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseOpenWidget.ui
  src/gui/KeePass1OpenWidget.cpp
  src/gui/OpVaultOpenWidget.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
  src/gui/masterkey/PasswordEditWidget.cpp
Labels: new feature, user interface, ux

#3306 Rework the Entry Preview panel
  CHANGELOG
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  src/gui/EntryPreviewWidget.ui
Labels: bounty :moneybag:, user interface

#3302 Add MinimizeOnOpenURL feature
  share/keepassxc.ini
  src/core/Config.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
Labels: ux

#3318 Fix broken build with YubiKey disabled
  src/gui/DatabaseOpenWidget.cpp
Labels: bug

#3336 Move notes to General tab on Group Preview Panel
  CHANGELOG
  src/cli/Analyze.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  src/gui/EntryPreviewWidget.ui
Labels: user interface

#3321 Add monospaced font option for Notes field
  CHANGELOG
  share/keepassxc.ini
  src/core/Config.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/EntryPreviewWidget.cpp
  src/gui/Font.cpp
  src/gui/Font.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/group/EditGroupWidget.cpp
Labels: user interface

#3253 Drop to background when copy feature
  CHANGELOG
  share/keepassxc.ini
  src/core/Config.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
Labels: ux

#3296 Correct application shortcut created by MSI Installer
  share/windows/wix-patch.xml
  share/windows/wix-template.xml
Labels: distribution, platform: Windows

#3303 FIX: Password generator skips special characters
  CHANGELOG
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
Labels: bug

#3332 Fix icon scaling for HiDPI displays
  src/main.cpp
Labels: user interface

#3344 Prompt to migrate KeePassHTTP settings only if Browser Integration is enabled
  src/browser/BrowserService.cpp
Labels: plugin: Browser integration

#3294 Add demo kdbx file (password is `secret`)
  share/demo.kdbx
  share/demo.key
Labels: documentation :bookmark_tabs:
