Repository keepassxreboot/keepassxc, pull requests merged in 2019-04, with the labels that each got.

#2919 Correct opening files from command line
  src/core/Database.cpp
  src/core/Database.h
  src/format/KdbxXmlReader.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/masterkey/KeyComponentWidget.cpp
  src/gui/masterkey/KeyComponentWidget.h
  src/gui/masterkey/PasswordEditWidget.cpp
  src/gui/masterkey/PasswordEditWidget.h
Labels: bug, high priority

#2933 Add integration with Brave browser (for Linux, OSX, and Windows)
  README.md
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/HostInstaller.cpp
  src/browser/HostInstaller.h
  utils/keepassxc-snap-helper.sh
Labels: plugin: Browser integration

#2946 Hotfix/#2820 more detailed share messages
  src/keeshare/KeeShare.cpp
  src/keeshare/ShareObserver.cpp
Labels: plugin: KeeShare

#2970 Enhance release-tool
  CMakeLists.txt
  release-tool
Labels: distribution

#2969 Hide window when performing entry auto-type on macOS
  src/autotype/AutoType.cpp
  src/autotype/AutoTypePlatformPlugin.h
  src/autotype/mac/AutoTypeMac.cpp
  src/autotype/mac/AutoTypeMac.h
  src/autotype/test/AutoTypeTest.cpp
  src/autotype/test/AutoTypeTest.h
Labels: platform: macOS, plugin: Auto-Type

#2968 Enhance update checker
  CMakeLists.txt
  src/CMakeLists.txt
  src/config-keepassx.h.cmake
  src/core/Clock.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/MainWindow.cpp
  src/updatecheck/UpdateChecker.cpp
  src/updatecheck/UpdateChecker.h
  tests/TestUpdateCheck.cpp
Labels: ux

#2982 Re-Add keys on database unlock
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: bug, plugin: SSH agent

#2990 GCC 5 / Ubuntu Xenial compilation
  src/keeshare/KeeShareSettings.cpp
Labels: bug, build system

#2985 Only remove keys on exit if they would remove on lock
  src/sshagent/SSHAgent.cpp
Labels: plugin: SSH agent, regression

#2984 Fix referenced entry color on macOS dark mode
  src/gui/entry/EntryModel.cpp
  src/gui/macutils/AppKit.h
  src/gui/macutils/AppKitImpl.h
  src/gui/macutils/AppKitImpl.mm
  src/gui/macutils/MacUtils.cpp
  src/gui/macutils/MacUtils.h
Labels: platform: macOS, user interface

#2978 Hotfix/2895 improved bulk file watcher
  src/core/FileWatcher.cpp
  src/core/FileWatcher.h
Labels: bug, plugin: KeeShare

#2987 Fix conditional build flags for yubikey and keeshare
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/dbsettings/DatabaseSettingsWidgetMasterKey.cpp
Labels: bug

#2997 Fix syntax highlighting in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#3001 Remove hardcoded background color from search help widget
  src/gui/SearchHelpWidget.ui
Labels: bug, platform: macOS, user interface

#2955 Add free text filter to Auto-Type dialog
  src/CMakeLists.txt
  src/autotype/AutoTypeFilterLineEdit.cpp
  src/autotype/AutoTypeFilterLineEdit.h
  src/autotype/AutoTypeSelectDialog.cpp
  src/autotype/AutoTypeSelectDialog.h
Labels: new feature, plugin: Auto-Type

#2972 Support for RFC-compliant TOTP hashes
  src/gui/TotpSetupDialog.cpp
  src/totp/totp.cpp
  src/totp/totp.h
  tests/TestTotp.cpp
Labels: new feature, plugin: TOTP

#2998 Fix toolbar text color on macOS when in dark mode
  src/gui/MainWindow.cpp
Labels: user interface

#2996 Add option to prefer DuckDuckGo
  src/core/Metadata.cpp
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/EditWidgetIcons.cpp
Labels: plugin: Networking

#3019 Remove apply button from application settings
  src/gui/ApplicationSettingsWidget.cpp
Labels: user interface

#3040 Correct CLI help messages on Windows
  src/cli/Add.cpp
  src/cli/Clip.cpp
  src/cli/Create.cpp
  src/cli/Diceware.cpp
  src/cli/Edit.cpp
  src/cli/Estimate.cpp
  src/cli/Extract.cpp
  src/cli/Generate.cpp
  src/cli/List.cpp
  src/cli/Locate.cpp
  src/cli/Merge.cpp
  src/cli/Remove.cpp
  src/cli/Show.cpp
Labels: bug, plugin: CLI

#3041 Don't mark entry edit as modified when attribute selection changes
  src/gui/entry/EditEntryWidget.cpp
Labels: bug, ux

#3039 Support Ctrl+Enter shortcut on all dialogs with QPushButtonBox
  src/gui/DialogyWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
Labels: ux

#3035 Use QLocale for translation search instead of custom method
  src/core/Translator.cpp
  src/core/Translator.h
Labels: user interface

#3026 Prevent infinite save loop when location is unavailable
  src/gui/DatabaseWidget.cpp
Labels: bug, high priority

#3025 Windows: use winqtdeploy instead of DeplyQt4 from CMake
  CMakeLists.txt
  cmake/CodeCoverage.cmake
  src/CMakeLists.txt
Labels: distribution, platform: Windows

#3020 Improve resilience against memory attacks
  CMakeLists.txt
  INSTALL.md
  src/CMakeLists.txt
  src/browser/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/core/Alloc.cpp
  src/keys/FileKey.cpp
  src/keys/FileKey.h
  src/keys/PasswordKey.cpp
  src/keys/PasswordKey.h
  src/keys/YkChallengeResponseKey.cpp
  src/keys/YkChallengeResponseKey.h
  src/proxy/CMakeLists.txt
  src/touchid/TouchID.mm
Labels: high priority, security

#3050 Set console code page to CP_UTF8 on Windows if supported.
  src/cli/TextStream.cpp
Labels: bug, i18n, platform: Windows

#3057 Snap: fix theming
  snap/local/launchers/README.md
  snap/local/launchers/gtk3-env-launch
  snap/snapcraft.yaml
  src/core/Bootstrap.cpp
Labels: distribution: Snap, user interface
