Repository keepassxreboot/keepassxc, pull requests merged in 2019-11, with the labels that each got.

#3710 CLI: do not display protected fields by default.
  share/docs/man/keepassxc-cli.1
  src/cli/Show.cpp
  src/cli/Show.h
  tests/TestCli.cpp
Labels: plugin: CLI, security

#3673 Check include malloc.h and malloc_usable_size(3)
  CMakeLists.txt
  src/core/Alloc.cpp
Labels: build system, security

#3777 Show application icon in Plasma Wayland sessions
  src/main.cpp
Labels: platform: Wayland

#3807 Make the purpose of the key file field clearer
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseOpenWidget.ui
Labels: ux

#3761 Secret Service Integration Fixes
  src/core/Tools.cpp
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/objects/SessionCipher.cpp
  src/fdosecrets/objects/SessionCipher.h
Labels: bug, plugin: Secret Service

#3775 Properly stylize the application name
  src/main.cpp
Labels: bug, platform: Linux

#3780 Improve UX of database statistics page
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.h
  src/gui/dbsettings/DatabaseSettingsWidgetStatistics.ui
Labels: bug, ux

#3826 Fix DatabaseUnlockDialog window sizing.
  src/gui/DatabaseOpenDialog.cpp
Labels: ux

#3727 Correct formatting of preview widget fields
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  src/gui/EntryPreviewWidget.ui
Labels: bug, user interface

#3827 Fix release-tool on macOS and add notarisation
  release-tool
  share/macosx/keepassxc.entitlements
Labels: build system, platform: macOS

#3832 Properly encode trailing equal signs for base32 encoded TOTP
  src/totp/totp.cpp
Labels: bug, plugin: TOTP

#3759 Fix URL matching with Browser Integration
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: bug, high priority :rotating_light:, plugin: Browser integration

#3854 Fix subdomain matching
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: bug, high priority :rotating_light:, plugin: Browser integration

#3871 FdoSecrets: fix crash when enabling the plugin on a non-exposed database
  src/fdosecrets/objects/Collection.h
  src/fdosecrets/objects/Service.cpp
Labels: bug, plugin: Secret Service

#3889 Release database before exiting CLI interactive mode
  src/cli/keepassxc-cli.cpp
Labels: bug, plugin: CLI

#3879 Only show warning about snap browsers on Linux
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
Labels: user interface

#3910 HTML encode url in ElidedLabel
  src/gui/widgets/ElidedLabel.cpp
Labels: bug

#3917 Fix typos in various .md files
  .github/ISSUE_TEMPLATE/release-preview-bug-report.md
  docs/KEYBINDS.md
  docs/QUICKSTART.md
  src/fdosecrets/README.md
Labels: documentation :bookmark_tabs:

#3919 INSTALL.md: fix broken wiki link
  INSTALL.md
Labels: documentation :bookmark_tabs:

#3914 FdoSecrets: handle the exposed group being moved to recycle bin
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.cpp
Labels: bug, plugin: Secret Service
