Repository keepassxreboot/keepassxc, pull requests merged in 2020-12, with the labels that each got.

#5726 Add Argon2id KDF
  src/crypto/kdf/Argon2Kdf.cpp
  src/crypto/kdf/Argon2Kdf.h
  src/format/KeePass2.cpp
  src/format/KeePass2.h
  src/format/OpVaultReader.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  tests/TestKdbx4.cpp
  tests/TestKeePass2Format.cpp
  tests/gui/TestGui.cpp
Labels: file format

#5610 Properly save Password Generator settings
  src/gui/PasswordGeneratorWidget.cpp
Labels: bug

#5760 Fix the warning about QTimer cannot be stopped from another thread
  src/core/Database.cpp
  src/core/Database.h
Labels: bug

#5778 Add Argon2id KDF (backport)
  src/cli/Import.cpp
  src/crypto/kdf/Argon2Kdf.cpp
  src/crypto/kdf/Argon2Kdf.h
  src/format/KeePass2.cpp
  src/format/KeePass2.h
  src/format/OpVaultReader.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  tests/TestKdbx4.cpp
  tests/TestKeePass2Format.cpp
  tests/gui/TestGui.cpp
Labels: backport, file format

#5724 Add delay to login startup on Linux
  src/gui/osutils/nixutils/NixUtils.cpp
Labels: platform: Linux

#5779 Hide keyfile path by default
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.ui
Labels: security

#5797 Hide actions when features are disabled
  src/gui/MainWindow.cpp
Labels: user interface

#5799 CODE-OF-CONDUCT.md: fix typo
  CODE-OF-CONDUCT.md
Labels: documentation :bookmark_tabs:

#5559 Fix re-select previously selected entry on database unlock
  src/gui/DatabaseWidget.cpp
Labels: bug

#5237 Add 'delete entry without confirm' functionality
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/DatabaseWidget.cpp
Labels: ux

#5812 Redo 'delete entries no confirm' functionality & unit-tests
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/DatabaseWidget.cpp
  tests/gui/TestGui.cpp
Labels: new feature, ux

#5820 Fix closing modal dialogs on database lock
  src/browser/BrowserService.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
Labels: bug, security

#5654 Display default autotype sequence on entry preview pane
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: new feature, plugin: Auto-Type

#5566 Move global shortcut handling into OSUtils
  CMakeLists.txt
  src/CMakeLists.txt
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
  src/autotype/AutoTypePlatformPlugin.h
  src/autotype/ShortcutWidget.cpp
  src/autotype/mac/AutoTypeMac.cpp
  src/autotype/mac/AutoTypeMac.h
  src/autotype/test/AutoTypeTest.cpp
  src/autotype/test/AutoTypeTest.h
  src/autotype/test/AutoTypeTestInterface.h
  src/autotype/windows/AutoTypeWindows.cpp
  src/autotype/windows/AutoTypeWindows.h
  src/autotype/xcb/AutoTypeXCB.cpp
  src/autotype/xcb/AutoTypeXCB.h
  src/gui/Application.cpp
  src/gui/Application.h
  src/gui/PasswordEdit.cpp
  src/gui/osutils/OSEventFilter.cpp
  src/gui/osutils/OSEventFilter.h
  src/gui/osutils/OSUtilsBase.h
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
  src/gui/osutils/nixutils/KeySymMap.h
  src/gui/osutils/nixutils/NixUtils.cpp
  src/gui/osutils/nixutils/NixUtils.h
  src/gui/osutils/nixutils/X11Funcs.cpp
  src/gui/osutils/nixutils/X11Funcs.h
  src/gui/osutils/nixutils/keysymmap.py
  src/gui/osutils/winutils/WinUtils.cpp
  src/gui/osutils/winutils/WinUtils.h
  src/gui/styles/dark/DarkStyle.cpp
  tests/TestAutoType.cpp
  tests/TestCli.cpp
  tests/TestCli.h
Labels: plugin: Auto-Type, refactor

#5798 Add support for version 2 XML key files
  src/cli/Utils.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/databasekey/KeyFileEditWidget.cpp
  src/keys/FileKey.cpp
  src/keys/FileKey.h
  tests/TestKeys.cpp
  tests/data/FileKeyXmlV2.kdbx
  tests/data/FileKeyXmlV2.keyx
  tests/data/FileKeyXmlV2BrokenHex.kdbx
  tests/data/FileKeyXmlV2BrokenHex.keyx
  tests/data/FileKeyXmlV2HashFail.kdbx
  tests/data/FileKeyXmlV2HashFail.keyx
Labels: file format

#5834 Hotfix/html preview
  src/gui/EntryPreviewWidget.cpp
Labels: bug, user interface

#5788 Remove offset on username field in classic theme
  src/gui/entry/EditEntryWidget.cpp
  src/gui/styles/base/BaseStyle.cpp
  src/gui/styles/base/classicstyle.qss
Labels: user interface

#5827 Prevent crash when KeeShare merges an entry that is in edit mode
  src/gui/entry/EditEntryWidget.cpp
  src/keeshare/ShareObserver.cpp
  src/keeshare/ShareObserver.h
Labels: crash :boom:, plugin: KeeShare

#5853 Prevent clipboard history and cloud sync on Windows
  src/gui/Clipboard.cpp
Labels: bug, platform: Windows, security

#5817 Copy history when drag/drop entries and groups
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/Group.cpp
  src/core/Group.h
  src/gui/group/GroupModel.cpp
  tests/gui/TestGui.cpp
Labels: bug

#5856 Patron Names and Debug Info
  src/crypto/Crypto.cpp
  src/gui/AboutDialog.cpp
Labels: documentation :bookmark_tabs:

#5860 Implement empty-area drag.
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: user interface, ux

#5862 Fix average password length in the Statistics report
  src/gui/reports/ReportsWidgetStatistics.cpp
Labels: bug, plugin: Reports

#5878 Always activate DatabaseOpenDialog on Windows
  src/gui/DatabaseOpenDialog.cpp
Labels: platform: Windows, plugin: Browser integration
