Repository keepassxreboot/keepassxc, pull requests merged in 2020-04, with the labels that each got.

#4546 Hide notes in entry view when hidden in preview panel
  src/gui/entry/EntryModel.cpp
Labels: security, user interface

#4531 Fix issues with HIBP report
  src/gui/reports/ReportsWidgetHibp.cpp
  src/gui/reports/ReportsWidgetHibp.h
  src/gui/reports/ReportsWidgetHibp.ui
Labels: bug, plugin: Reports

#4406 Set expiration time to Now when enabling entry expiration
  src/gui/entry/EditEntryWidget.cpp
Labels: platform: Linux

#4560 Perform one KDF benchmark at a time
  src/crypto/kdf/Kdf.cpp
Labels: bug, high priority :rotating_light:

#4323 On Unix, copy to clipboard using wl-clipboard if xclip is not available
  src/cli/Utils.cpp
  tests/TestCli.cpp
Labels: platform: Linux, plugin: CLI

#4564 Fix macOS 10.15.4 codesigning crash
  CMakeLists.txt
  release-tool
  share/macosx/Info.plist.cmake
  share/macosx/embedded.provisionprofile
  share/macosx/keepassxc.entitlements
  src/CMakeLists.txt
Labels: build system, high priority :rotating_light:, platform: macOS

#4569 Fix install of libssl and libcrypto on Windows build
  src/CMakeLists.txt
Labels: bug, build system

#4441 Ability to disable animation of message widget
  src/gui/MessageWidget.cpp
  src/gui/MessageWidget.h
  src/keeshare/group/EditGroupWidgetKeeShare.cpp
Labels: bug, user interface

#4589 Recycle KeePassHTTP settings
  src/browser/BrowserService.cpp
Labels: plugin: Browser integration

#4614 Update Issue and Pull Request templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/release-preview-bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation :bookmark_tabs:

#4643 Stop file checksum compare when stop is called
  src/core/FileWatcher.cpp
Labels: bug

#4677 Fix tabbar separator visibility
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug, user interface
