Repository keepassxreboot/keepassxc, pull requests merged in 2020-02, with the labels that each got.

#4272 Code Style: Add braces around single line statements
  src/core/CsvParser.cpp
  src/core/Entry.cpp
  src/core/Tools.cpp
  src/format/HtmlExporter.cpp
  src/gui/FileDialog.cpp
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/csvImport/CsvParserModel.cpp
  src/gui/group/GroupView.cpp
  src/gui/widgets/ElidedLabel.cpp
  tests/TestCsvParser.cpp
  tests/TestSymmetricCipher.cpp
  tests/TestYkChallengeResponseKey.cpp
Labels: not a bug

#3918 Code Style: Fixes for minor issues found by static analysis
  src/autotype/xcb/AutoTypeXCB.cpp
  src/core/ScreenLockListenerWin.h
  src/gui/EditWidgetIcons.cpp
  src/gui/MainWindow.cpp
  src/gui/MessageBox.cpp
  tests/TestSymmetricCipher.cpp
Labels: not a bug

#4305 Fix browser-like DbTab experience with macOS and Windows
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug, platform: macOS

#4288 Do not add duplicate entries
  src/browser/BrowserService.cpp
Labels: bug, plugin: Browser integration

#4337 Distinguish meaning of src directory and git root directory
  INSTALL.md
Labels: documentation :bookmark_tabs:

#4354 Icon downloader button crash fix
  src/core/IconDownloader.cpp
Labels: bug

#4256 SSH Agent: Allow toggling integration on and off without restart
  src/gui/DatabaseWidget.cpp
  src/gui/EditWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/sshagent/AgentSettingsWidget.cpp
  src/sshagent/AgentSettingsWidget.ui
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: plugin: SSH agent

#4287 Return keyboard focus after saving database edits
  src/gui/DatabaseWidget.cpp
Labels: bug, ux

#4368 Fix clearing search field when using application
  src/gui/SearchWidget.cpp
  src/gui/SearchWidget.h
Labels: bug, ux

#4336 Fix window hiding right after being shown on X11, fix window not minimizing in X11
  src/core/Clock.cpp
  src/core/Clock.h
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
Labels: bug, platform: Linux, user interface
