Repository keepassxreboot/keepassxc, pull requests merged in 2020-01, with the labels that each got.

#4036 FdoSecrets: fix searching of entries with special characters in attributes
  src/fdosecrets/objects/Collection.cpp
  tests/TestFdoSecrets.cpp
  tests/TestFdoSecrets.h
Labels: bug, plugin: Secret Service

#4074 FdoSecrets: only emit completed signal when the action actually finishes
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/objects/Collection.h
  src/fdosecrets/objects/Prompt.cpp
  src/fdosecrets/objects/Prompt.h
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/objects/Service.h
  src/gui/DatabaseOpenDialog.cpp
  src/gui/DatabaseOpenDialog.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
Labels: bug, plugin: Secret Service

#4104 CMakeLists.txt: Do not unconditionally use ccache
  CMakeLists.txt
Labels: build system

#4129 Use SHA256 Digest for Code Signing on Windows
  release-tool
Labels: build system, platform: Windows

#4131 Only use bare minimum settings for portable version
  share/keepassxc.ini
Labels: distribution, platform: Windows

#4132 Prevent crash if Auto-Type performed on new entry
  src/autotype/AutoType.cpp
Labels: crash :boom:

#4150 Backport: Prevent crash if Auto-Type performed on new entry
  src/autotype/AutoType.cpp
Labels: backport, crash :boom:

#4153 Prevent unnecessary merge requests on intermittent network shares
  src/core/FileWatcher.cpp
Labels: bug

#4147 Ensure challenge-response key buffer is properly cleared.
  src/core/Database.cpp
  tests/CMakeLists.txt
  tests/TestKdbx3.cpp
  tests/TestKdbx4.cpp
  tests/TestKdbx4.h
  tests/TestKeePass2Format.cpp
  tests/TestKeePass2Format.h
Labels: bug, high priority :rotating_light:

#4134 Add empty path to URL when needed
  src/browser/BrowserService.cpp
Labels: bug, plugin: Browser integration

#4172 Don't mark cmd:// urls as invalid
  src/core/Tools.cpp
Labels: bug, plugin: Browser integration

#3359 Add integration with Edge browser (Chromium-based)
  README.md
  src/browser/BrowserOptionDialog.cpp
  src/browser/BrowserOptionDialog.ui
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/HostInstaller.cpp
  src/browser/HostInstaller.h
Labels: new feature, plugin: Browser integration

#4156 Prevent crash when all entries are deleted from a group
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.h
  tests/gui/TestGui.cpp
Labels: crash :boom:

#4165 Fix clearing clipboad on Gnome
  src/gui/Clipboard.cpp
  src/gui/Clipboard.h
Labels: bug, platform: Linux

#4155 Prevent proxy host from blocking application shutdown
  src/browser/NativeMessagingBase.cpp
Labels: bug, plugin: Browser integration

#4210 Fix AppImage builds due to missing PNG app icons
  share/icons/application/256x256/apps/keepassxc.png
Labels: ci, distribution: AppImage, distribution: Snap

#4086 Use stderr for help text on error.
  src/cli/keepassxc-cli.cpp
Labels: plugin: CLI

#4211 Exit with error code if AppImage creation fails midair
  release-tool
Labels: build system, ci, distribution: AppImage

#4214 Retrieve login1 session object from manager
  src/core/ScreenLockListenerDBus.cpp
  src/core/ScreenLockListenerDBus.h
Labels: bug, platform: Linux

#4189 Fix CLI man page and change both man pages
  share/docs/man/keepassxc-cli.1
  share/docs/man/keepassxc.1
Labels: documentation :bookmark_tabs:, plugin: CLI

#4247 Removing QColor (from Qt::Widgets) from core modules.
  src/core/Compare.cpp
  src/core/Compare.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/Metadata.cpp
  src/core/Metadata.h
  src/format/KdbxXmlReader.cpp
  src/format/KdbxXmlReader.h
  src/format/KdbxXmlWriter.cpp
  src/format/KdbxXmlWriter.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryModel.cpp
  tests/TestKeePass2Format.cpp
  tests/TestModified.cpp
  tests/gui/TestGui.cpp
Labels: plugin: CLI, refactor

#4231 Adding db-info CLI command.
  CHANGELOG.md
  share/docs/man/keepassxc-cli.1
  src/cli/CMakeLists.txt
  src/cli/Command.cpp
  src/cli/Info.cpp
  src/cli/Info.h
  src/crypto/kdf/AesKdf.cpp
  src/crypto/kdf/AesKdf.h
  src/crypto/kdf/Argon2Kdf.cpp
  src/crypto/kdf/Argon2Kdf.h
  src/crypto/kdf/Kdf.h
  src/format/KeePass2.cpp
  tests/TestCli.cpp
  tests/TestCli.h
Labels: new feature, plugin: CLI

#4227 Small cleanup in cli/Show.cpp
  src/cli/Show.cpp
Labels: plugin: CLI

#3833 SSH Agent: Refactor entry and agent key management
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/sshagent/KeeAgentSettings.cpp
  src/sshagent/KeeAgentSettings.h
  src/sshagent/SSHAgent.cpp
Labels: plugin: SSH agent, refactor

#4063 Enable browser-like DbTab experience (Alt + Nums)
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: new feature, ux

#4224 Add challenge-response recovery tool
  utils/keepassxc-cr-recovery/.gitignore
  utils/keepassxc-cr-recovery/README.md
  utils/keepassxc-cr-recovery/go.mod
  utils/keepassxc-cr-recovery/go.sum
  utils/keepassxc-cr-recovery/main.go
Labels: plugin: YubiKey

#3769 Implement SSH key file path env substitution
  src/core/Tools.cpp
  src/core/Tools.h
  src/sshagent/KeeAgentSettings.cpp
  src/sshagent/KeeAgentSettings.h
  tests/TestTools.cpp
  tests/TestTools.h
Labels: new feature, plugin: SSH agent

#3801 SSH Agent: Add SSH_AUTH_SOCK override and connection test
  src/sshagent/AgentSettingsWidget.cpp
  src/sshagent/AgentSettingsWidget.ui
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: new feature, plugin: SSH agent

#3834 Cleanup UI files
  src/browser/BrowserOptionDialog.ui
  src/cli/Export.cpp
  src/cli/Import.cpp
  src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.cpp
  src/fdosecrets/widgets/DatabaseSettingsWidgetFdoSecrets.ui
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/EditWidgetIcons.ui
  src/gui/PasswordGeneratorWidget.ui
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.ui
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetAutoType.ui
  src/gui/group/EditGroupWidgetMain.ui
  src/gui/wizard/NewDatabaseWizardPage.ui
  src/keeshare/group/EditGroupWidgetKeeShare.ui
Labels: user interface

#4114 CLI: set decryption time on create.
  share/docs/man/keepassxc-cli.1
  src/cli/Create.cpp
  src/cli/Create.h
  src/crypto/kdf/Kdf.h
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.h
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.ui
  tests/TestCli.cpp
Labels: plugin: CLI

#4161 Ignore system icon theme, always use our own icons
  src/core/FilePath.cpp
  src/core/FilePath.h
  src/fdosecrets/widgets/SettingsModels.cpp
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
  src/gui/KMessageWidget.cpp
  src/gui/LineEdit.cpp
  src/gui/masterkey/PasswordEditWidget.cpp
  src/keeshare/group/EditGroupWidgetKeeShare.cpp
  utils/makeicons.sh
Labels: user interface

#4203 Use entry action icons without any frame
  share/icons/application/scalable/actions/entry-clone.svg
  share/icons/application/scalable/actions/entry-delete.svg
  share/icons/application/scalable/actions/entry-edit.svg
  share/icons/application/scalable/actions/entry-new.svg
Labels: user interface

#2143 Improve confirm access dialog for browser plugin
  src/browser/BrowserAccessControlDialog.cpp
  src/browser/BrowserAccessControlDialog.h
  src/browser/BrowserAccessControlDialog.ui
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: plugin: Browser integration, ux

#4128 FdoSecrets: check and show PID and executable for existing secret service process
  src/fdosecrets/FdoSecretsPlugin.cpp
  src/fdosecrets/FdoSecretsPlugin.h
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.h
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.ui
Labels: new feature, plugin: Secret Service

#3921 Wrap XML data into QString to fix encoding
  src/cli/Export.cpp
  src/cli/TextStream.cpp
  src/cli/TextStream.h
Labels: plugin: CLI

#3947 Add --username option to Clip command.
  share/docs/man/keepassxc-cli.1
  src/cli/Clip.cpp
  src/cli/Clip.h
  src/cli/Show.cpp
  src/cli/Utils.cpp
  src/cli/Utils.h
  tests/TestCli.cpp
  tests/data/NewDatabase.kdbx
Labels: plugin: CLI
