Repository keepassxreboot/keepassxc, pull requests merged in 2020-07, with the labels that each got.

#4929 Replace "Master Key" with "Database Credentials"
  src/CMakeLists.txt
  src/core/Database.cpp
  src/core/Database.h
  src/core/Metadata.cpp
  src/core/Metadata.h
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/objects/Service.h
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
  src/format/Kdbx3Reader.cpp
  src/format/Kdbx3Writer.cpp
  src/format/Kdbx4Reader.cpp
  src/format/Kdbx4Writer.cpp
  src/format/KdbxXmlReader.cpp
  src/format/KdbxXmlWriter.cpp
  src/format/KeePass1Reader.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseOpenWidget.ui
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/databasekey/KeyComponentWidget.cpp
  src/gui/databasekey/KeyComponentWidget.h
  src/gui/databasekey/KeyComponentWidget.ui
  src/gui/databasekey/KeyFileEditWidget.cpp
  src/gui/databasekey/KeyFileEditWidget.h
  src/gui/databasekey/KeyFileEditWidget.ui
  src/gui/databasekey/PasswordEditWidget.cpp
  src/gui/databasekey/PasswordEditWidget.h
  src/gui/databasekey/PasswordEditWidget.ui
  src/gui/databasekey/YubiKeyEditWidget.cpp
  src/gui/databasekey/YubiKeyEditWidget.h
  src/gui/databasekey/YubiKeyEditWidget.ui
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.h
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.h
  src/gui/wizard/NewDatabaseWizard.cpp
  src/gui/wizard/NewDatabaseWizardPageDatabaseKey.cpp
  src/gui/wizard/NewDatabaseWizardPageDatabaseKey.h
  tests/TestKeePass2Format.cpp
  tests/gui/TestGui.cpp
Labels: documentation :bookmark_tabs:, refactor

#4909 Hide window after unlock dialog
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, platform: macOS, plugin: Browser integration

#5004 Fix slot detection when first YubiKey is configured on slot 2
  src/keys/drivers/YubiKey.cpp
Labels: bug, plugin: YubiKey

#5011 Reset icon theme name before calling QIcon::fromTheme().
  src/core/Resources.cpp
Labels: bug, platform: Linux, user interface

#5084 Improve restart requests
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/MainWindow.cpp
Labels: ux

#5005 Prevent crash if focus widget gets deleted during saving
  src/gui/DatabaseWidget.cpp
Labels: crash :boom:

#5031 Add OARS metadata
  share/linux/org.keepassxc.KeePassXC.appdata.xml
Labels: platform: Linux

#5030 Partially fix appdata screenshots
  share/linux/org.keepassxc.KeePassXC.appdata.xml
Labels: platform: Linux

#5056 Skip referenced passwords in Health check report
  src/core/PasswordHealth.cpp
Labels: bug, plugin: Reports

#5116 Substitute tilde with USERPROFILE on Windows
  src/core/Tools.cpp
  tests/TestTools.cpp
Labels: bug, plugin: SSH agent

#5115 SSH Agent: Always forget all keys on lock
  src/sshagent/SSHAgent.cpp
Labels: bug, plugin: SSH agent

#5106 Fix crash if TOTP digits exceeds 10
  src/core/Entry.cpp
  src/totp/totp.cpp
Labels: crash :boom:, plugin: TOTP

#5121 Unbreak build with Ninja
  docs/CMakeLists.txt
Labels: build system

#5124 PasswordEdit use CTRL modifier on all platforms
  src/gui/PasswordEdit.cpp
Labels: bug, platform: macOS

#5064 Add Qt translation dir for RPM packaging
  src/core/Translator.cpp
Labels: platform: Linux

#4971 Add support for the Xfce screensaver
  src/core/ScreenLockListenerDBus.cpp
Labels: platform: Linux, security

#4967 Linux .desktop file: Add available translations for GenericName
  share/linux/org.keepassxc.KeePassXC.desktop
Labels: documentation :bookmark_tabs:, platform: Linux

#5140 Fix 'db-info' command name to show it right in 'help'
  src/cli/Info.cpp
Labels: documentation :bookmark_tabs:, plugin: CLI

#4832 Adjust matching with best-matching credentials enabled
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: plugin: Browser integration

#4891 Add option to auto-type just the username/password
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
Labels: new feature, plugin: Auto-Type

#5010 Improve man pages with useful links and copyright
  docs/man/keepassxc-cli.1.adoc
  docs/man/keepassxc.1.adoc
  docs/man/section-copyright.adoc
  docs/man/section-notes.adoc
  docs/man/section-reporting-bugs.adoc
Labels: documentation :bookmark_tabs:, plugin: CLI

#4956 Open and save attachment in readonly mode
  src/gui/entry/EntryAttachmentsWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.h
Labels: ux

#5184 Clear clipboard on database lock
  src/gui/Clipboard.cpp
Labels: security

#5191 Switch to classic if theme set to auto and high contast mode is on
  src/gui/Application.cpp
  src/gui/osutils/winutils/WinUtils.cpp
  src/gui/osutils/winutils/WinUtils.h
Labels: accessibility, platform: Windows, user interface
