Repository keepassxreboot/keepassxc, pull requests merged in 2020-06, with the labels that each got.

#4803 Optimise KeePassXC logo icons and improve compatibility.
  share/icons/application/256x256/apps/keepassxc.png
  share/icons/application/scalable/apps/keepassxc-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-dark-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-dark.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-light-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-light.svg
  share/icons/application/scalable/apps/keepassxc-unlocked.svg
  share/icons/application/scalable/apps/keepassxc.svg
Labels: bug

#4807 Enable shadow warnings on GCC and tweak CMake
  CMakeLists.txt
  src/CMakeLists.txt
  src/fdosecrets/objects/Collection.cpp
  src/keeshare/ShareExport.cpp
Labels: build system

#4808 Fix loading of tray icon appearance setting
  src/core/Resources.cpp
  src/core/Resources.h
  src/gui/ApplicationSettingsWidget.cpp
Labels: bug, user interface

#4822 Cleanup welcome screen recent databases view
  src/gui/WelcomeWidget.cpp
  src/gui/WelcomeWidget.h
Labels: user interface

#4827 Fix minor UX issues with DB Open Widget
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseOpenWidget.ui
  src/gui/KeePass1OpenWidget.cpp
Labels: ux

#4833 Fix permissions changing on database save
  src/core/Database.cpp
  src/keys/FileKey.cpp
  tests/gui/TestGuiFdoSecrets.cpp
Labels: bug, security

#4841 Reduce compiler flag warnings depending on language
  CMakeLists.txt
Labels: build system

#4874 Remove connection to non-existent signal
  src/browser/BrowserService.cpp
Labels: plugin: Browser integration

#4873 Fix activating entries in database reports when sorted
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHealthcheck.h
  src/gui/reports/ReportsWidgetHibp.cpp
  src/gui/reports/ReportsWidgetHibp.h
Labels: bug, plugin: Reports

#4848 On case-sensitive OS, force use of lowercase config directory
  src/core/Config.cpp
Labels: bug

#4883 Browser: Check for expired entry prior to custom data
  src/browser/BrowserService.cpp
Labels: bug, plugin: Browser integration

#4884 FDO Secrets: Fix double free on exit
  src/fdosecrets/FdoSecretsPlugin.cpp
  src/fdosecrets/FdoSecretsPlugin.h
  tests/gui/TestGuiFdoSecrets.cpp
Labels: bug, crash :boom:, plugin: Secret Service

#4902 SSH Agent: Fix regression in context menu hotkeys
  src/gui/MainWindow.ui
Labels: PRE-RELEASE BUG, plugin: SSH agent, regression

#4912 Fix --pw-stdin by initializing text streams
  src/main.cpp
Labels: bug

#4897 Remove redundant call to update tray icon during startup
  src/gui/MainWindow.cpp
Labels: bug, platform: Linux

#4886 Fix Touch ID timeout not being set correctly
  src/gui/MainWindow.cpp
Labels: bug, platform: macOS

#4872 Fix auto-start settings on Windows
  share/windows/wix-template.xml
  src/gui/osutils/winutils/WinUtils.cpp
Labels: bug, platform: Windows

#4915 Call `QGuiApplication::setHighDpiScaleFactorRoundingPolicy` to fix #2815
  src/main.cpp
Labels: user interface

#4892 Fix layout of CSV Import Widget
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/csvImport/CsvImportWidget.h
  src/gui/csvImport/CsvImportWidget.ui
Labels: bug, user interface
