Repository keepassxreboot/keepassxc, pull requests merged in 2020-05, with the labels that each got.

#4665 Refactor Config
  src/autotype/AutoType.cpp
  src/autotype/AutoTypeSelectDialog.cpp
  src/browser/BrowserSettings.cpp
  src/core/Bootstrap.cpp
  src/core/Config.cpp
  src/core/Config.h
  src/core/Group.cpp
  src/core/IconDownloader.cpp
  src/core/PasswordGenerator.h
  src/core/Resources.cpp
  src/core/Translator.cpp
  src/fdosecrets/FdoSecretsSettings.cpp
  src/gui/Application.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/Clipboard.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidgetStateSync.cpp
  src/gui/EditWidgetIcons.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/FileDialog.cpp
  src/gui/IconDownloaderDialog.cpp
  src/gui/MainWindow.cpp
  src/gui/PasswordEdit.cpp
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/SearchWidget.cpp
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/WelcomeWidget.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.cpp
  src/gui/entry/EntryModel.cpp
  src/gui/group/EditGroupWidget.cpp
  src/keeshare/KeeShare.cpp
  src/keeshare/KeeShare.h
  src/keeshare/SettingsWidgetKeeShare.cpp
  src/keeshare/ShareObserver.cpp
  src/keeshare/group/EditGroupWidgetKeeShare.cpp
  src/sshagent/SSHAgent.cpp
  src/updatecheck/UpdateChecker.cpp
  tests/TestAutoType.cpp
  tests/gui/TestGui.cpp
  tests/gui/TestGuiBrowser.cpp
Labels: refactor

#3646 Implement Caps Lock warning for password input
  src/CMakeLists.txt
  src/core/Resources.cpp
  src/core/Resources.h
  src/gui/PasswordEdit.cpp
  src/gui/PasswordEdit.h
  src/gui/osutils/OSUtilsBase.h
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
  src/gui/osutils/nixutils/NixUtils.cpp
  src/gui/osutils/nixutils/NixUtils.h
  src/gui/osutils/winutils/WinUtils.cpp
  src/gui/osutils/winutils/WinUtils.h
Labels: new feature, ux

#4695 Fix menu menu spacing on low-DPI Windows
  src/gui/styles/base/BaseStyle.cpp
Labels: user interface

#4707 Make CLI clip test more reliable
  tests/TestCli.cpp
Labels: ci, tests

#4697 Add xclip into snap
  snap/snapcraft.yaml
Labels: distribution: Snap, plugin: CLI

#4706 Fix "Minimise at startup" on Windows
  src/core/Bootstrap.cpp
Labels: bug, platform: Windows

#4617 Show "New Entry" in the context menu even if an item is selected
  src/gui/MainWindow.cpp
Labels: ux

#4542 Allow entries to be excluded from Health Check and HIBP
  COPYING
  share/demo.kdbx
  share/icons/application/scalable/actions/reports-exclude.svg
  share/icons/application/scalable/actions/reports.svg
  share/icons/icons.qrc
  src/core/PasswordHealth.cpp
  src/core/PasswordHealth.h
  src/gui/MainWindow.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetAdvanced.ui
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHealthcheck.h
  src/gui/reports/ReportsWidgetHealthcheck.ui
  src/gui/reports/ReportsWidgetHibp.cpp
  src/gui/reports/ReportsWidgetHibp.h
  src/gui/reports/ReportsWidgetHibp.ui
  src/gui/reports/ReportsWidgetStatistics.cpp
  src/gui/reports/ReportsWidgetStatistics.ui
  tests/gui/TestGui.cpp
  utils/makeicons.sh
Labels: new feature, plugin: Reports

#4714 Fix snap build
  snap/snapcraft.yaml
Labels: distribution: Snap

#4720 Fix various issues with KeeShare
  src/core/Database.cpp
  src/core/FileWatcher.cpp
  src/core/FileWatcher.h
  src/gui/FileDialog.cpp
  src/gui/FileDialog.h
  src/keeshare/KeeShare.cpp
  src/keeshare/ShareObserver.cpp
  src/keeshare/ShareObserver.h
  src/keeshare/group/EditGroupWidgetKeeShare.cpp
  src/keeshare/group/EditGroupWidgetKeeShare.h
Labels: bug, plugin: KeeShare

#4715 Change settings checkbox texts to positive phrasing
  src/core/Config.cpp
  src/core/Config.h
  src/core/Group.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/EntryPreviewWidget.cpp
  src/gui/PasswordEdit.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryModel.cpp
  tests/CMakeLists.txt
  tests/TestConfig.cpp
  tests/TestConfig.h
  tests/data/OutdatedConfig.ini
Labels: ux

#4630 Improve OPVault handling and replace test opvault
  src/format/OpVaultReader.cpp
  src/format/OpVaultReaderAttachments.cpp
  src/format/OpVaultReaderBandEntry.cpp
  src/format/OpVaultReaderSections.cpp
  src/gui/DatabaseTabWidget.cpp
  tests/TestOpVaultReader.cpp
  tests/TestOpVaultReader.h
  tests/data/freddy-2013-12-04.opvault.txt
  tests/data/freddy-2013-12-04.opvault/default/1C7D72EFA19A4EE98DB7A9661D2F5732_3B94A1F475014E27BFB00C99A42214DF.attachment
  tests/data/freddy-2013-12-04.opvault/default/2A632FDD32F5445E91EB5636C7580447_8FA293F2B001459D8F8F78C21E6BF9F6.attachment
  tests/data/freddy-2013-12-04.opvault/default/E0D293D29B10483F8DFDAC72ED0BE5C0_898CD4CD00164930A2E15B159CE65E8F.attachment
  tests/data/freddy-2013-12-04.opvault/default/F2DB5DA3FCA64372A751E0E85C67A538_23F6167DC1FB457A8DE7033ACDCD06DB.attachment
  tests/data/freddy-2013-12-04.opvault/default/F2DB5DA3FCA64372A751E0E85C67A538_AFBDA49A5F684179A78161E40CA2AAD3.attachment
  tests/data/freddy-2013-12-04.opvault/default/FF445AB1497241A28812363154E1A738_16684B74F26145169EC03B950DC68E95.attachment
  tests/data/freddy-2013-12-04.opvault/default/band_0.js
  tests/data/freddy-2013-12-04.opvault/default/band_1.js
  tests/data/freddy-2013-12-04.opvault/default/band_2.js
  tests/data/freddy-2013-12-04.opvault/default/band_3.js
  tests/data/freddy-2013-12-04.opvault/default/band_4.js
  tests/data/freddy-2013-12-04.opvault/default/band_5.js
  tests/data/freddy-2013-12-04.opvault/default/band_6.js
  tests/data/freddy-2013-12-04.opvault/default/band_7.js
  tests/data/freddy-2013-12-04.opvault/default/band_8.js
  tests/data/freddy-2013-12-04.opvault/default/band_A.js
  tests/data/freddy-2013-12-04.opvault/default/band_D.js
  tests/data/freddy-2013-12-04.opvault/default/band_E.js
  tests/data/freddy-2013-12-04.opvault/default/band_F.js
  tests/data/freddy-2013-12-04.opvault/default/folders.js
  tests/data/freddy-2013-12-04.opvault/default/profile.js
  tests/data/keepassxc.opvault/default/30B6513EE64B4DFE9C47EC2F257CE296_34034F6E478A4D4F91CDBE0A077E2128.attachment
  tests/data/keepassxc.opvault/default/band_1.js
  tests/data/keepassxc.opvault/default/band_3.js
  tests/data/keepassxc.opvault/default/band_4.js
  tests/data/keepassxc.opvault/default/band_5.js
  tests/data/keepassxc.opvault/default/band_A.js
  tests/data/keepassxc.opvault/default/band_C.js
  tests/data/keepassxc.opvault/default/folders.js
  tests/data/keepassxc.opvault/default/profile.js
Labels: bug, import: OPVault

#4623 CLI: Use stderr for password prompts and improve tests
  src/cli/Add.cpp
  src/cli/AddGroup.cpp
  src/cli/Analyze.cpp
  src/cli/Clip.cpp
  src/cli/Command.cpp
  src/cli/Create.cpp
  src/cli/DatabaseCommand.cpp
  src/cli/Diceware.cpp
  src/cli/Edit.cpp
  src/cli/Estimate.cpp
  src/cli/Export.cpp
  src/cli/Generate.cpp
  src/cli/Help.cpp
  src/cli/Import.cpp
  src/cli/Info.cpp
  src/cli/List.cpp
  src/cli/Locate.cpp
  src/cli/Merge.cpp
  src/cli/Move.cpp
  src/cli/Remove.cpp
  src/cli/RemoveGroup.cpp
  src/cli/Show.cpp
  src/cli/Utils.cpp
  src/cli/Utils.h
  src/cli/keepassxc-cli.cpp
  src/format/KdbxWriter.h
  src/keys/YkChallengeResponseKeyCLI.cpp
  src/keys/YkChallengeResponseKeyCLI.h
  tests/TestCli.cpp
  tests/TestCli.h
Labels: bug, high priority :rotating_light:, plugin: CLI, refactor

#4705 Add group search
  src/core/EntrySearcher.cpp
  src/core/EntrySearcher.h
  src/gui/SearchHelpWidget.ui
  tests/TestEntrySearcher.cpp
  tests/TestEntrySearcher.h
Labels: new feature

#4600 Set URL placeholder text to https://example.com
  src/gui/entry/EditEntryWidgetMain.ui
Labels: user interface

#4584 Significantly enhance hardware key robustness
  src/cli/Command.cpp
  src/cli/Utils.cpp
  src/cli/Utils.h
  src/core/Alloc.cpp
  src/core/Database.cpp
  src/core/Database.h
  src/format/Kdbx3Reader.cpp
  src/format/Kdbx3Writer.cpp
  src/format/Kdbx4Reader.cpp
  src/format/Kdbx4Writer.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseOpenWidget.ui
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/masterkey/YubiKeyEditWidget.cpp
  src/gui/masterkey/YubiKeyEditWidget.h
  src/keys/ChallengeResponseKey.h
  src/keys/CompositeKey.cpp
  src/keys/CompositeKey.h
  src/keys/YkChallengeResponseKey.cpp
  src/keys/YkChallengeResponseKey.h
  src/keys/YkChallengeResponseKeyCLI.cpp
  src/keys/YkChallengeResponseKeyCLI.h
  src/keys/drivers/YubiKey.cpp
  src/keys/drivers/YubiKey.h
  src/keys/drivers/YubiKeyStub.cpp
  tests/CMakeLists.txt
  tests/TestCli.cpp
  tests/TestYkChallengeResponseKey.cpp
  tests/TestYkChallengeResponseKey.h
Labels: high priority :rotating_light:, plugin: YubiKey, refactor

#4641 Fix changing focus around the main window using tab
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/SearchWidget.cpp
  src/gui/group/GroupView.cpp
  src/gui/group/GroupView.h
  tests/gui/TestGui.cpp
Labels: bug, ux

#4508 Deactivate read-only mode autodetection. Fixes #803.
  src/core/Database.cpp
Labels: bug

#4591 Allow manual editing of browser extension connection keys & add option for custom extension ID
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/BrowserSettingsWidget.cpp
  src/browser/BrowserSettingsWidget.ui
  src/browser/NativeMessageInstaller.cpp
  src/core/Config.cpp
  src/core/Config.h
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.h
Labels: new feature, plugin: Browser integration

#4747 Make GUI tests more robust for CI
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: ci

#4746 Fix browser socket path for proxy and app
  src/browser/BrowserShared.cpp
Labels: bug, plugin: Browser integration

#4550 Add "Save Database Backup..." feature
  COPYING
  share/icons/application/scalable/actions/document-save-copy.svg
  share/icons/icons.qrc
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
  utils/makeicons.sh
Labels: new feature

#4660 Fix annoyances with access control dialog
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, plugin: Browser integration

#4685 Fix merging browser keys
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/core/CustomData.cpp
  src/core/CustomData.h
  src/core/Merger.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
Labels: bug, plugin: Browser integration

#4745 Add button to hide pre-release warning for this release.
  src/core/Config.cpp
  src/core/Config.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
Labels: ux

#3698 Use unlock dialog when unlocking a database from browser extension
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/MainWindow.cpp
Labels: plugin: Browser integration

#4549 SSH Agent: Fix attachment data not updating before apply
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/KeeAgentSettings.cpp
  src/sshagent/KeeAgentSettings.h
Labels: bug, plugin: SSH agent, regression

#4545 SSH Agent: Track which database owns a key for remove-on-lock
  src/gui/DatabaseWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
  tests/TestSSHAgent.cpp
  tests/TestSSHAgent.h
Labels: bug, plugin: SSH agent

#4769 Use Segoe UI font on Windows.
  src/core/Bootstrap.cpp
Labels: platform: Windows, user interface

#4148 Add custom browser option
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/BrowserSettingsWidget.cpp
  src/browser/BrowserSettingsWidget.h
  src/browser/BrowserSettingsWidget.ui
  src/browser/BrowserShared.h
  src/browser/NativeMessageInstaller.cpp
  src/core/Config.cpp
  src/core/Config.h
Labels: new feature, plugin: Browser integration

#4357 Implement feature "custom entry sort order"
  COPYING
  share/icons/application/scalable/actions/move-down.svg
  share/icons/application/scalable/actions/move-up.svg
  share/icons/icons.qrc
  src/core/Database.cpp
  src/core/Database.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/Group.cpp
  src/core/Group.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/entry/EntryModel.cpp
  src/gui/entry/EntryModel.h
  src/gui/entry/EntryView.cpp
  src/gui/entry/EntryView.h
  tests/TestEntry.cpp
  tests/TestEntry.h
  tests/TestEntryModel.cpp
  tests/TestGroup.cpp
  tests/TestGroup.h
  utils/makeicons.sh
Labels: new feature, ux

#4526 Reset database path after failed 'save as'
  src/gui/DatabaseWidget.cpp
Labels: bug

#4595 SSH Agent: Reset settings when KeeAgent.settings is removed
  src/gui/DatabaseWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/sshagent/KeeAgentSettings.cpp
  src/sshagent/KeeAgentSettings.h
Labels: bug, plugin: SSH agent

#4651 Issue a warning before adding large attachments
  src/gui/entry/EntryAttachmentsWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.h
Labels: user interface

#4776 Fix DatabaseTabWidget::lockDatabases returns false even when all tabs are locked
  src/gui/DatabaseTabWidget.cpp
Labels: bug

#4780 Check correct CMake flag.
  src/CMakeLists.txt
Labels: build system

#4782 Hide window and dock icon on macOS when tray enabled
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/osutils/macutils/AppKit.h
  src/gui/osutils/macutils/AppKitImpl.h
  src/gui/osutils/macutils/AppKitImpl.mm
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
Labels: platform: macOS, ux

#4232 FdoSecrets: Add unit tests for secret service integration
  src/core/EntrySearcher.cpp
  src/core/EntrySearcher.h
  src/fdosecrets/FdoSecretsPlugin.cpp
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/objects/Collection.h
  src/fdosecrets/objects/DBusObject.h
  src/fdosecrets/objects/DBusTypes.cpp
  src/fdosecrets/objects/Item.cpp
  src/fdosecrets/objects/Item.h
  src/fdosecrets/objects/Prompt.cpp
  src/fdosecrets/objects/Prompt.h
  src/fdosecrets/objects/Session.cpp
  src/fdosecrets/objects/SessionCipher.cpp
  src/fdosecrets/objects/SessionCipher.h
  src/fdosecrets/widgets/SettingsModels.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  tests/CMakeLists.txt
  tests/TestEntrySearcher.cpp
  tests/TestEntrySearcher.h
  tests/data/dbus/interfaces/org.freedesktop.Secret.Collection.xml
  tests/data/dbus/interfaces/org.freedesktop.Secret.Item.xml
  tests/data/dbus/interfaces/org.freedesktop.Secret.Prompt.xml
  tests/data/dbus/interfaces/org.freedesktop.Secret.Service.xml
  tests/data/dbus/interfaces/org.freedesktop.Secret.Session.xml
  tests/data/dbus/session.conf
  tests/gui/CMakeLists.txt
  tests/gui/TestGuiFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.h
Labels: plugin: Secret Service, tests

#4791 Clean up various parts of the UI and rearrange settings
  share/demo.kdbx
  src/core/Database.cpp
  src/core/Global.h
  src/gui/AboutDialog.ui
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/CategoryListWidget.ui
  src/gui/DatabaseOpenWidget.ui
  src/gui/EditWidget.ui
  src/gui/EditWidgetIcons.cpp
  src/gui/EditWidgetIcons.ui
  src/gui/EditWidgetProperties.ui
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
  src/gui/IconDownloaderDialog.ui
  src/gui/csvImport/CsvImportWidget.ui
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.ui
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetAdvanced.ui
  src/gui/entry/EditEntryWidgetAutoType.ui
  src/gui/entry/EditEntryWidgetMain.ui
  src/gui/entry/EditEntryWidgetSSHAgent.ui
  src/gui/group/EditGroupWidgetMain.ui
  src/gui/reports/ReportsWidgetHealthcheck.ui
  src/gui/reports/ReportsWidgetHibp.ui
  src/gui/reports/ReportsWidgetStatistics.ui
  src/keeshare/SettingsWidgetKeeShare.ui
  src/keeshare/group/EditGroupWidgetKeeShare.ui
  src/sshagent/AgentSettingsWidget.cpp
  src/sshagent/AgentSettingsWidget.h
  src/sshagent/AgentSettingsWidget.ui
  tests/TestCsvExporter.cpp
  tests/gui/TestGui.cpp
Labels: bug, theme

#4796 Add option for monochrome tray icon
  share/icons/application/scalable/apps/keepassxc-dark.svg
  share/icons/application/scalable/apps/keepassxc-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-dark-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-dark.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-light-locked.svg
  share/icons/application/scalable/apps/keepassxc-monochrome-light.svg
  share/icons/application/scalable/apps/keepassxc-unlocked.svg
  share/icons/application/scalable/apps/keepassxc.svg
  share/icons/icons.qrc
  src/core/Config.cpp
  src/core/Config.h
  src/core/Resources.cpp
  src/core/Resources.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/styles/base/BaseStyle.cpp
Labels: user interface
