Repository keepassxreboot/keepassxc, pull requests merged in 2020-08, with the labels that each got.

#5129 Improve Password Generator Widget UI/UX
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
  src/gui/PasswordGeneratorWidget.ui
  src/gui/styles/base/basestyle.qss
Labels: user interface, ux

#5227 Fix clipped labels when Light/Dark theme is used
  src/gui/CategoryListWidget.cpp
Labels: bug, user interface

#5214 Only display domain name in browser access confirm dialog
  src/browser/BrowserAccessControlDialog.cpp
  src/browser/BrowserAccessControlDialog.h
  src/browser/BrowserService.cpp
Labels: plugin: Browser integration, user interface

#5228 Update "Open Auto-Type help webpage" URL
  src/gui/entry/EditEntryWidget.cpp
Labels: documentation :bookmark_tabs:

#5197 Fix "Search Results" banner improperly themed
  src/gui/Application.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/styles/base/basestyle.qss
  src/gui/styles/base/classicstyle.qss
  src/gui/styles/styles.qrc
Labels: theme

#5123 Fix removing open databases setting
  src/gui/ApplicationSettingsWidget.cpp
Labels: bug

#5210 Fixup saving non-data changes on database lock
  src/core/Config.cpp
  src/core/Config.h
  src/core/Database.cpp
  src/core/Database.h
  src/core/Group.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  tests/TestConfig.cpp
Labels: ux

#5266 Fix excessive memory usage by icons
  src/core/DatabaseIcons.cpp
  src/core/Metadata.cpp
  src/core/Resources.cpp
Labels: bug, user interface

#5278 Add command for retrieving the current TOTP
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: new feature, plugin: Browser integration

#5082 Change actions for F1-F2-F3 keys
  docs/topics/KeyboardShortcuts.adoc
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/SearchWidget.h
  tests/gui/TestGui.cpp
Labels: bug, user interface

#5267 Improve button hover effect for checked buttons
  src/gui/styles/base/basestyle.qss
  src/gui/styles/dark/darkstyle.qss
  src/gui/styles/light/lightstyle.qss
Labels: user interface

#5283 Add show/hide expired entries on global AutoType
  src/autotype/AutoType.cpp
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
Labels: plugin: Auto-Type

#5294 Add note for macOS Keyboard shortcuts
  docs/styles/dark.css
  docs/topics/KeyboardShortcuts.adoc
Labels: documentation :bookmark_tabs:
