Repository keepassxreboot/keepassxc, pull requests merged in 2020-10, with the labels that each got.

#5484 Fix SSH Add/Remove Key Shortcut on macOS
  src/gui/MainWindow.cpp
Labels: bug, platform: macOS

#5276 Describe HTML export/paper backups in the user manual
  docs/topics/ImportExport.adoc
Labels: documentation :bookmark_tabs:

#5476 Improve CMakeLists.txt and docs/CMakeLists.txt
  CMakeLists.txt
  docs/CMakeLists.txt
Labels: build system

#5513 Remove GUI bootstraping from core/
  src/cli/keepassxc-cli.cpp
  src/core/Bootstrap.cpp
  src/core/Bootstrap.h
  src/gui/Application.cpp
  src/gui/Application.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/main.cpp
  tests/TestCli.cpp
  tests/gui/TestGui.cpp
  tests/gui/TestGuiBrowser.cpp
  tests/gui/TestGuiFdoSecrets.cpp
Labels: refactor

#4647 Add fuzz test support to keepassxc-cli
  docs/FuzzTest.md
  share/empty3.kdbx
  share/empty4.kdbx
  src/cli/Utils.cpp
Labels: plugin: CLI, tests

#5394 Add feature to ignore entries for HTTP-Auth Logins
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetBrowser.ui
Labels: new feature, plugin: Browser integration

#5402 Add keyfile option to keepassxc cli import cmd
  docs/man/keepassxc-cli.1.adoc
  src/cli/Create.cpp
  src/cli/Create.h
  src/cli/Import.cpp
  src/cli/Utils.cpp
  src/cli/Utils.h
  tests/TestCli.cpp
Labels: new feature, plugin: CLI

#5545 Fix crash when toggling capslock rapidly
  src/gui/PasswordEdit.cpp
Labels: crash :boom:

#5542 Final push for 2.6.2
  src/core/Config.cpp
  src/core/Config.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/DatabaseWidgetStateSync.cpp
  src/gui/DatabaseWidgetStateSync.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryModel.cpp
  src/gui/entry/EntryModel.h
  src/gui/entry/EntryView.cpp
  src/gui/entry/EntryView.h
  src/keeshare/ShareObserver.cpp
  utils/keepassxc-snap-helper.sh
Labels: bug

#5536 Prevent data loss when drag/drop between databases
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/Group.cpp
  src/core/Group.h
  src/gui/group/GroupModel.cpp
Labels: bug

#5535 Add search 'by-path' url for browser
  src/browser/BrowserService.cpp
  src/core/Entry.cpp
  src/core/Entry.h
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: new feature, plugin: Browser integration

#5483 Force set entry preview after search ends
  src/gui/DatabaseWidget.cpp
Labels: bug

#5560 Place database credentials widget in scroll area
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  src/gui/wizard/NewDatabaseWizardPage.cpp
  src/gui/wizard/NewDatabaseWizardPage.ui
  src/gui/wizard/NewDatabaseWizardPageDatabaseKey.cpp
  src/gui/wizard/NewDatabaseWizardPageDatabaseKey.h
Labels: bug, user interface
