Repository keepassxreboot/keepassxc, pull requests merged in 2021-10, with the labels that each got.

#6999 Add feature to sort groups using shortcut keys
  src/gui/group/GroupView.cpp
Labels: user interface

#6930 Add countdown progress bar to TOTP preview
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
Labels: user interface

#6915 FdoSecrets: Improve client executable path handling
  share/translations/keepassxc_en.ts
  src/fdosecrets/dbus/DBusClient.cpp
  src/fdosecrets/dbus/DBusClient.h
  src/fdosecrets/dbus/DBusMgr.cpp
  src/fdosecrets/dbus/DBusMgr.h
  src/fdosecrets/objects/Prompt.cpp
  src/fdosecrets/widgets/AccessControlDialog.cpp
  src/fdosecrets/widgets/AccessControlDialog.h
  src/fdosecrets/widgets/AccessControlDialog.ui
  src/fdosecrets/widgets/SettingsModels.cpp
  src/fdosecrets/widgets/SettingsModels.h
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.cpp
Labels: feature: Secret Service

#6675 Add TOTP option to entry level Auto-Type menu
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
Labels: feature: Auto-Type

#7004 Place the 'Recycle Bin' at the bottom of the list when groups are sorted.
  src/core/Group.cpp
Labels: user interface

#7010 Correct naming of newly generated keyx files
  src/gui/databasekey/KeyFileEditWidget.cpp
Labels: bug
