Repository keepassxreboot/keepassxc, pull requests merged in 2021-05, with the labels that each got.

#6481 fix showing any notes in an entry without notes (Fixes #6461)
  src/gui/EntryPreviewWidget.cpp
Labels: bug, user interface

#6507 Remove obsolete cmake helper files
  cmake/FindArgon2.cmake
  cmake/FindGcrypt.cmake
  cmake/FindLibGPGError.cmake
  cmake/Findsodium.cmake
Labels: build system

#6392 Auto-Type: Resolve username/password when copying to clipboard
  src/autotype/AutoTypeSelectDialog.cpp
Labels: bug, plugin: Auto-Type

#6363 Set permissions of saved attachments to be private to the current user
  src/gui/entry/EntryAttachmentsWidget.cpp
Labels: security

#6514 Fix unreachable setting of file permissions
  src/core/Database.cpp
Labels: bug

#6279 Show search bar when toolbar is hidden or overflow
  src/CMakeLists.txt
  src/gui/DatabaseWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/SearchWidget.cpp
  src/gui/SearchWidget.h
  src/gui/widgets/KPToolBar.cpp
  src/gui/widgets/KPToolBar.h
Labels: bug

#6338 MinimizeAfterUnlock also when unlocking through browser
  src/gui/DatabaseWidget.cpp
Labels: bug, platform: macOS, plugin: Browser integration

#6511 Add command line option to lock open databases
  src/gui/Application.cpp
  src/gui/Application.h
  src/main.cpp
Labels: new feature

#6530 Auto-Type: Allow selection of modal dialogs on X11
  src/autotype/AutoTypeSelectDialog.cpp
  src/gui/entry/AutoTypeMatchView.cpp
Labels: backport

#6443 Fix challenge-response key data after Botan
  src/CMakeLists.txt
  src/cli/Utils.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/databasekey/YubiKeyEditWidget.cpp
  src/gui/databasekey/YubiKeyEditWidget.h
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  src/keys/ChallengeResponseKey.cpp
  src/keys/ChallengeResponseKey.h
  src/keys/CompositeKey.cpp
  src/keys/CompositeKey.h
  src/keys/YkChallengeResponseKey.h
  tests/TestYkChallengeResponseKey.cpp
  tests/mock/MockChallengeResponseKey.cpp
  tests/mock/MockChallengeResponseKey.h
Labels: bug, high priority :rotating_light:, plugin: YubiKey

#6534 Add a checkbox to health report allowing to exclude expired entries
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHealthcheck.ui
Labels: new feature, ux

#6438 Properly block modified signal during Database destruction
  src/CMakeLists.txt
  src/core/AutoTypeAssociations.cpp
  src/core/AutoTypeAssociations.h
  src/core/CustomData.cpp
  src/core/CustomData.h
  src/core/Database.cpp
  src/core/Database.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/EntryAttachments.cpp
  src/core/EntryAttachments.h
  src/core/EntryAttributes.cpp
  src/core/EntryAttributes.h
  src/core/Group.cpp
  src/core/Group.h
  src/core/Metadata.cpp
  src/core/Metadata.h
  src/core/ModifiableObject.cpp
  src/core/ModifiableObject.h
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/objects/Item.cpp
  src/fdosecrets/objects/Service.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/EditWidgetProperties.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/group/EditGroupWidget.cpp
  src/keeshare/ShareObserver.cpp
  src/keeshare/group/EditGroupWidgetKeeShare.cpp
  tests/TestDatabase.cpp
  tests/TestGroup.cpp
  tests/TestMerge.cpp
  tests/TestModified.cpp
  tests/TestModified.h
Labels: bug, crash :boom:

#6512 add a button to reveal protected attributes in entry view (addresses Issue #1930)
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
Labels: user interface, ux

#6560 Detect quazip >= 1.0 via pkgconfig
  cmake/FindQuaZip.cmake
  src/keeshare/CMakeLists.txt
Labels: build system

#6537 Add a context menu entry to delete entries from health check reports
  src/CMakeLists.txt
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/GuiTools.cpp
  src/gui/GuiTools.h
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHealthcheck.h
  src/gui/reports/ReportsWidgetHealthcheck.ui
  src/gui/reports/ReportsWidgetHibp.cpp
  src/gui/reports/ReportsWidgetHibp.h
  src/gui/reports/ReportsWidgetHibp.ui
Labels: new feature, plugin: Reports
