Repository keepassxreboot/keepassxc, pull requests merged in 2021-02, with the labels that each got.

#6039 Fix *.so files not being signed resulting in notarization errors
  release-tool
Labels: build system, platform: macOS

#6030 Prevent screen capture on Windows
  src/gui/osutils/OSUtilsBase.cpp
  src/gui/osutils/OSUtilsBase.h
  src/gui/osutils/macutils/AppKit.h
  src/gui/osutils/macutils/AppKitImpl.h
  src/gui/osutils/macutils/AppKitImpl.mm
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
  src/gui/osutils/nixutils/NixUtils.h
  src/gui/osutils/winutils/WinUtils.cpp
  src/gui/osutils/winutils/WinUtils.h
  src/main.cpp
Labels: security

#6050 Use macdeployqt for all executables
  CMakeLists.txt
  src/CMakeLists.txt
  src/autotype/mac/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/proxy/CMakeLists.txt
Labels: bug, build system, platform: macOS

#6108 Allow setting MSI properties in unattended install
  share/windows/wix-template.xml
Labels: distribution, platform: Windows

#6149 Update MainWindow minimum size to enable smaller verticle space
  src/gui/MainWindow.ui
Labels: user interface

#6174 Add file extension if user omitted (Keeshare)
  src/keeshare/ShareExport.cpp
  src/keeshare/ShareImport.cpp
Labels: crash :boom:, plugin: KeeShare

#5970 Purge unused custom icons and bulk deletion of icons
  COPYING
  share/icons/application/scalable/actions/hammer-wrench.svg
  share/icons/icons.qrc
  src/CMakeLists.txt
  src/gui/EditWidgetIcons.cpp
  src/gui/EditWidgetIcons.h
  src/gui/EditWidgetIcons.ui
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/dbsettings/DatabaseSettingsDialog.h
  src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.h
  src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.ui
Labels: new feature, ux
