Repository keepassxreboot/keepassxc, pull requests merged in 2021-11, with the labels that each got.

#7098 Auto-Type: Reimplement X11 keysym emulation
  src/autotype/xcb/AutoTypeXCB.cpp
  src/autotype/xcb/AutoTypeXCB.h
Labels: platform: Linux, feature: Auto-Type, regression

#7100 Add Microsoft Edge support for Linux
  src/browser/BrowserSettingsWidget.cpp
  src/browser/NativeMessageInstaller.cpp
Labels: new feature, feature: Browser

#6799 Support for wordlists in user configuration directory
  COPYING
  share/icons/application/scalable/actions/trash.svg
  share/icons/icons.qrc
  share/translations/keepassxc_en.ts
  src/core/Resources.cpp
  src/core/Resources.h
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
  src/gui/PasswordGeneratorWidget.ui
Labels: new feature, Hacktoberfest

#7035 Allow specifing database backup paths.
  share/translations/keepassxc_en.ts
  src/cli/Add.cpp
  src/cli/AddGroup.cpp
  src/cli/Create.cpp
  src/cli/Edit.cpp
  src/cli/Import.cpp
  src/cli/Merge.cpp
  src/cli/Move.cpp
  src/cli/Remove.cpp
  src/cli/RemoveGroup.cpp
  src/core/Config.cpp
  src/core/Config.h
  src/core/Database.cpp
  src/core/Database.h
  src/core/Tools.cpp
  src/core/Tools.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
  tests/TestDatabase.cpp
  tests/TestTools.cpp
  tests/TestTools.h
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: new feature, Hacktoberfest

#6280 Removing QWidget dependency from src/core.
  CMakeLists.txt
  src/CMakeLists.txt
  src/autotype/AutoTypeMatchModel.cpp
  src/cli/CMakeLists.txt
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/Global.h
  src/core/Group.cpp
  src/core/Group.h
  src/core/Merger.cpp
  src/core/Metadata.cpp
  src/core/Metadata.h
  src/core/Tools.cpp
  src/core/Tools.h
  src/fdosecrets/widgets/AccessControlDialog.cpp
  src/fdosecrets/widgets/SettingsModels.cpp
  src/format/KdbxXmlReader.cpp
  src/format/KdbxXmlWriter.cpp
  src/format/KdbxXmlWriter.h
  src/format/KeePass1Reader.cpp
  src/gui/DatabaseIcons.cpp
  src/gui/DatabaseIcons.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/EditWidgetIcons.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/HtmlExporter.cpp
  src/gui/HtmlExporter.h
  src/gui/IconDownloaderDialog.cpp
  src/gui/IconModels.cpp
  src/gui/Icons.cpp
  src/gui/Icons.h
  src/gui/dbsettings/DatabaseSettingsWidgetMaintenance.cpp
  src/gui/entry/EntryModel.cpp
  src/gui/group/GroupModel.cpp
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHibp.cpp
  src/keeshare/KeeShare.cpp
  src/keeshare/KeeShareSettings.cpp
  src/keeshare/ShareExport.cpp
  src/qrcode/CMakeLists.txt
  tests/TestEntryModel.cpp
  tests/TestGroup.cpp
  tests/TestKeePass1Reader.cpp
  tests/TestKeePass2Format.cpp
  tests/TestMerge.cpp
  tests/gui/TestGuiPixmaps.cpp
Labels: refactor

#7071 Fix entry preview resetting when focusing out of entry view
  src/gui/entry/EntryView.cpp
  src/gui/entry/EntryView.h
Labels: PRE-RELEASE BUG

#7104 Fix crash while downloading favicon
  src/gui/IconDownloaderDialog.cpp
Labels: crash :boom:

#7011 Support sorting HTML export
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/HtmlExporter.cpp
  src/gui/HtmlExporter.h
  src/gui/export/ExportDialog.cpp
  src/gui/export/ExportDialog.h
  src/gui/export/ExportDialog.ui
Labels: new feature, feature: Reports, Hacktoberfest

#7117 fix compilation on macOS when clang<9 & Qt<5.12
  src/core/Alloc.cpp
  src/gui/osutils/macutils/AppKitImpl.mm
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/styles/base/BaseStyle.cpp
  src/touchid/TouchID.mm
Labels: platform: macOS

#7160 Fix syntax issue & add a missing header
  src/core/CustomData.cpp
  src/core/Metadata.cpp
  tests/TestTools.cpp
Labels: platform: macOS

#7166 SSH Agent: Show correct error messages in main window
  src/gui/DatabaseWidget.cpp
Labels: bug, feature: SSH agent

#7161 Fix transient save errors in TestGui
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: tests

#7129 Auto-Type: Remember previous selected global match
  docs/topics/AutoType.adoc
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
  src/autotype/AutoTypeMatchModel.cpp
  src/autotype/AutoTypeMatchModel.h
  src/autotype/AutoTypeMatchView.cpp
  src/autotype/AutoTypeMatchView.h
  src/autotype/AutoTypeSelectDialog.cpp
  src/autotype/AutoTypeSelectDialog.h
Labels: feature: Auto-Type

#7180 bump to the C++17 standard in the build system
  CMakeLists.txt
Labels: build system
