Repository keepassxreboot/keepassxc, pull requests merged in 2022-04, with the labels that each got.

#7764 SSH Agent: Fix Windows agent selection, radio buttons
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/sshagent/AgentSettingsWidget.cpp
  src/sshagent/AgentSettingsWidget.ui
Labels: bug, feature: SSH agent, backport-pending

#7771 Revert DatabaseOpenDialog to be always on top on Linux
  src/gui/DatabaseOpenDialog.cpp
Labels: regression, platform: Linux - KDE

#7755 Improve speed of AES KDF transform
  src/crypto/kdf/AesKdf.cpp
Labels: bug, backport-pending

#7767 Improve Entry Preview layout
  src/gui/EntryPreviewWidget.ui
  src/gui/entry/EditEntryWidgetMain.ui
  src/gui/styles/base/basestyle.qss
Labels: bug, user interface, backport-pending

#7728 Upstream Flathub patches
  CMakeLists.txt
  share/CMakeLists.txt
  share/linux/keepassxc.xml.in
  share/linux/org.keepassxc.KeePassXC.appdata.xml
  share/linux/org.keepassxc.KeePassXC.desktop.in
  src/browser/BrowserSettingsWidget.cpp
  src/browser/BrowserShared.cpp
  src/browser/NativeMessageInstaller.cpp
  src/config-keepassx.h.cmake
  src/core/EntryAttachments.cpp
  src/gui/Icons.cpp
  src/gui/Icons.h
  utils/keepassxc-flatpak-wrapper.sh
Labels: distribution: Flatpak

#7798 Remove "latest" tag from release name
  CMakeLists.txt
Labels: build system

#7864 Normalize path (slashes to be precise) when opening a database or saving the last used database paths (Fixes #7821)
  src/gui/MainWindow.cpp
  src/main.cpp
Labels: bug, user interface, platform: Windows

#7807 thirdparty/ykcore: link against libpthread
  src/thirdparty/ykcore/CMakeLists.txt
Labels: build system
