Repository keepassxreboot/keepassxc, pull requests merged in 2022-03, with the labels that each got.

#7479 Fix deployment of keepassxc-cli and keepassxc-proxy and the autotype plugin
  CMakeLists.txt
  cmake/KPXCHelpers.cmake
  src/autotype/mac/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/proxy/CMakeLists.txt
Labels: platform: macOS, build system, PRE-RELEASE BUG

#7497 Revert back to reference Argon2 library
  CMakeLists.txt
  src/CMakeLists.txt
  src/crypto/kdf/Argon2Kdf.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  utils/vcpkg_ports/argon2/CMakeLists.txt
  utils/vcpkg_ports/argon2/portfile.cmake
  utils/vcpkg_ports/argon2/vcpkg.json
Labels: high priority :rotating_light:, PRE-RELEASE BUG

#7503 Update contributors and Patrons on About Dialog
  src/gui/AboutDialog.cpp
  utils/transifex_translators.py
Labels: documentation :bookmark_tabs:

#7498 Fix missing include in alloc preventing some secure deallocations
  src/core/Alloc.cpp
Labels: high priority :rotating_light:, PRE-RELEASE BUG

#7508 Add the SEE ALSO to man pages
  docs/man/keepassxc-cli.1.adoc
  docs/man/keepassxc.1.adoc
Labels: documentation :bookmark_tabs:

#7520 Retain quick unlock if Hardware Key is missing
  src/gui/DatabaseOpenWidget.cpp
Labels: bug, feature: QuickUnlock

#7527 Skip "StatusIndicator" window in Auto-Type window list (backport)
  src/autotype/mac/AutoTypeMac.cpp
  src/autotype/mac/AutoTypeMac.h
Labels: platform: macOS, feature: Auto-Type, backport

#7526 Skip "StatusIndicator" window in Auto-Type window list
  src/autotype/mac/AutoTypeMac.cpp
  src/autotype/mac/AutoTypeMac.h
Labels: platform: macOS, feature: Auto-Type

#7523 Generate the D-Bus adaptor class on the fly
  src/CMakeLists.txt
  src/gui/MainWindow.cpp
  src/gui/MainWindowAdaptor.cpp
  src/gui/MainWindowAdaptor.h
Labels: bug, platform: Linux

#7544 Fix release-tool on macOS
  release-tool
Labels: platform: macOS, build system

#7432 Change "open" to "Open" in Windows context menu
  share/windows/wix-patch.xml
Labels: user interface

#7500 Allow colon in tags and sort alphabetically
  src/core/Entry.cpp
Labels: PRE-RELEASE BUG, feature: Tags

#7556 Run macdeployqt once at install time
  CMakeLists.txt
  cmake/KPXCHelpers.cmake
  cmake/KPXCMacDeployHelpers.cmake
  src/CMakeLists.txt
  src/autotype/mac/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/post_install/CMakeLists.txt
  src/proxy/CMakeLists.txt
Labels: platform: macOS, build system

#7558 Update release tool with new merge strategy
  .github/CONTRIBUTING.md
  .github/pull.yml
  CHANGELOG.md
  release-tool
  release-tool.ps1
  snap/snapcraft.yaml
Labels: build system, PRE-RELEASE BUG

#7471 FdoSecrets: allow to remember decision for future entries
  share/translations/keepassxc_en.ts
  src/fdosecrets/dbus/DBusClient.cpp
  src/fdosecrets/dbus/DBusClient.h
  src/fdosecrets/objects/Prompt.cpp
  src/fdosecrets/objects/Prompt.h
  src/fdosecrets/widgets/AccessControlDialog.cpp
  src/fdosecrets/widgets/AccessControlDialog.h
  src/fdosecrets/widgets/AccessControlDialog.ui
  src/fdosecrets/widgets/SettingsWidgetFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.h
Labels: ux, feature: Secret Service

#7561 Fix check for malloc_usable_size()
  CMakeLists.txt
Labels: platform: Linux, build system, backport-pending

#7588 Correct timing issue with entry level Auto-Type on some platforms
  src/autotype/AutoType.cpp
Labels: bug, feature: Auto-Type, backport-pending

#7587 Fix missing Auto-Type from snap package
  snap/snapcraft.yaml
Labels: distribution: Snap, backport-pending

#7598 Reduce delay when searching entries in Auto-Type select dialog
  src/autotype/AutoTypeSelectDialog.cpp
  src/autotype/AutoTypeSelectDialog.h
Labels: feature: Auto-Type, backport-pending

#7648 Fix compilation on macOS < 12.0.1 (touchid)
  src/touchid/TouchID.mm
Labels: platform: macOS, build system, backport-pending

#7614 Auto-Type: Map ASCII dead keys on Linux
  src/autotype/xcb/AutoTypeXCB.cpp
  src/autotype/xcb/AutoTypeXCB.h
Labels: platform: Linux, feature: Auto-Type, backport-pending

#7594 CLI: Add missing parameters to add/edit commands
  src/cli/Add.cpp
  src/cli/Edit.cpp
Labels: bug, feature: CLI, backport-pending

#7708 Several improvements to tags editing
  src/core/Entry.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/tag/TagsEdit.cpp
  tests/gui/TestGui.cpp
Labels: bug, feature: Tags, backport-pending

#7725 Fix regression: Hide password before unlocking database
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseWidget.cpp
Labels: bug, high priority :rotating_light:, security, regression, backport-pending

#7628 Use setChangeCurrentOnDrag property to handle drag and drop between tabs
  src/CMakeLists.txt
  src/gui/DatabaseTabWidget.cpp
  src/gui/DragTabBar.cpp
  src/gui/DragTabBar.h
Labels: bug, user interface, platform: Linux - Wayland, backport-pending

#7738 Add 12 hours expiration preset
  share/translations/keepassxc_en.ts
  src/core/TimeDelta.cpp
  src/core/TimeDelta.h
  src/gui/entry/EditEntryWidget.cpp
Labels: user interface, new feature
