Repository keepassxreboot/keepassxc, pull requests merged in 2022-06, with the labels that each got.

#8042 Add config variable for specifying a default file name for the database
  src/core/Config.cpp
  src/core/Config.h
  src/gui/DatabaseWidget.cpp
Labels: new feature, backport-pending

#8009 Add database backup path documentation.
  docs/topics/DatabaseOperations.adoc
  docs/topics/Reference.adoc
Labels: documentation :bookmark_tabs:, backport-pending

#8022 FdoSecrets: ask to unlock the database before storing entries
  src/fdosecrets/objects/Prompt.cpp
  src/fdosecrets/objects/Prompt.h
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/objects/Service.h
  tests/gui/TestGuiFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.h
Labels: feature: Secret Service, backport-pending

#8028 FdoSecrets: only show unlock dialog when there is no unlocked & exposed database
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/objects/Service.cpp
  src/fdosecrets/objects/Service.h
  src/gui/DatabaseTabWidget.h
  tests/gui/TestGuiFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.h
Labels: feature: Secret Service, backport-pending

#7442 docs: Explicitly talk about SSH Agent integration
  README.md
  docs/topics/SSHAgent.adoc
Labels: documentation :bookmark_tabs:, backport-pending

#7994 Fix file dialog not appearing on snap build
  src/core/Bootstrap.cpp
Labels: bug, distribution: Snap, backport-pending

#8111 Fix use of modifiers under macOS
  src/autotype/mac/AutoTypeMac.cpp
  src/autotype/mac/AutoTypeMac.h
  src/gui/osutils/macutils/MacUtils.cpp
Labels: platform: macOS, feature: Auto-Type, backport-pending

#7995 Fix Auto-Type gui guard for tests
  src/autotype/AutoType.cpp
Labels: bug, feature: Auto-Type, backport-pending

#8114 Pass database locked/unlocked status even with Search In All Opened Databases option enabled
  src/browser/BrowserService.cpp
Labels: bug, feature: Browser

#7778 Capture original regex in non-matching group when an exact match is r…
  src/core/Tools.cpp
  src/core/Tools.h
  tests/TestEntrySearcher.cpp
  tests/TestFdoSecrets.cpp
  tests/TestTools.cpp
  tests/TestTools.h
Labels: bug, backport-pending

#7987 Fix autotype menu entries on Windows
  src/autotype/AutoTypeSelectDialog.cpp
Labels: bug, feature: Auto-Type, backport-pending

#7993 Improve entry preview panel
  share/translations/keepassxc_en.ts
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
Labels: bug, user interface, backport-pending

#8118 Auto-Type: PICKCHARS can specify attribute and ignore BEEP
  share/translations/keepassxc_en.ts
  src/autotype/AutoType.cpp
  tests/TestAutoType.cpp
Labels: feature: Auto-Type, backport-pending

#8055 Add methods isHardwareKeySupported and refreshHardwareKeys to DBus
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/org.keepassxc.KeePassXC.MainWindow.xml
Labels: platform: Linux, backport-pending

#7968 Update eff_large.wordlist
  share/wordlists/eff_large.wordlist
Labels: backport-pending

#8116 Emit database changed signal when locking a single database
  src/gui/DatabaseTabWidget.cpp
Labels: bug, feature: Browser, backport-pending

#8134 Add vcs-browser and contribute URLs to Appdata
  share/linux/org.keepassxc.KeePassXC.appdata.xml
Labels: documentation :bookmark_tabs:

#7988 Browser feature: Add omit WWW subdomain group option
  share/translations/keepassxc_en.ts
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/group/EditGroupWidget.cpp
  src/gui/group/EditGroupWidgetBrowser.ui
  tests/TestBrowser.cpp
Labels: new feature, feature: Browser, backport-pending

#8144 Fix crash when trying to close database during unlock
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseWidget.cpp
Labels: crash :boom:

#7795 cmake: emit warning if X11_Xi or X11_XTest not found
  src/autotype/CMakeLists.txt
Labels: build system, feature: Auto-Type
