Repository keepassxreboot/keepassxc, pull requests merged in 2022-01, with the labels that each got.

#6487 Add tag functionality (Issue #508)
  COPYING
  cmake/CLangFormat.cmake
  share/icons/application/scalable/actions/tag-search.svg
  share/icons/application/scalable/actions/tag.svg
  share/icons/application/scalable/categories/label.svg
  share/icons/icons.qrc
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/core/Config.cpp
  src/core/Config.h
  src/core/Database.cpp
  src/core/Database.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/EntrySearcher.cpp
  src/core/EntrySearcher.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/DatabaseWidgetStateSync.cpp
  src/gui/DatabaseWidgetStateSync.h
  src/gui/EntryPreviewWidget.cpp
  src/gui/EntryPreviewWidget.ui
  src/gui/MainWindow.cpp
  src/gui/SearchWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetMain.ui
  src/gui/styles/base/basestyle.qss
  src/gui/styles/base/classicstyle.qss
  src/gui/tag/TagModel.cpp
  src/gui/tag/TagModel.h
  src/gui/tag/TagsEdit.cpp
  src/gui/tag/TagsEdit.h
  tests/gui/TestGui.cpp
Labels: user interface, new feature, EPIC, ux

#7254 Fix wildcard window title matching in Auto-Type
  src/core/Entry.cpp
  src/core/EntrySearcher.cpp
  src/core/Tools.cpp
  src/core/Tools.h
  src/fdosecrets/objects/Collection.cpp
  tests/TestTools.cpp
  tests/TestTools.h
Labels: feature: Auto-Type, PRE-RELEASE BUG

#7322 Fix access denied errors when using KeeShare export/sync
  src/keeshare/ShareExport.cpp
  src/keeshare/ShareImport.cpp
Labels: high priority :rotating_light:, PRE-RELEASE BUG

#7315 Fixes #7304 - Update tab order for CSV import dialog to match screen order
  src/gui/csvImport/CsvImportWidget.ui
Labels: user interface

#7212 Fix security settings on MSVC build
  CMakeLists.txt
Labels: build system

#7359 Fix new password generator closed reply with Browser Integration
  src/browser/BrowserService.cpp
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
Labels: bug, feature: Browser

#7274 Add powershell version of release-tool
  cmake/MakePortableZip.cmake
  release-tool
  release-tool.ps1
  src/CMakeLists.txt
Labels: build system

#7290 Show expired entries on DB unlock
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
Labels: new feature
