Repository keepassxreboot/keepassxc, pull requests merged in 2022-05, with the labels that each got.

#7831 Fix capture of whiptail's exit status
  utils/keepassxc-snap-helper.sh
Labels: bug, distribution: Snap, backport-pending

#7867 clang-tidy: use range loop
  src/gui/styles/base/BaseStyle.cpp
Labels: build system, refactor

#7868 clang-tidy: use override
  src/cli/AddGroup.h
  src/cli/Info.h
  src/cli/Move.h
  src/cli/Remove.h
  src/cli/RemoveGroup.h
  src/cli/Show.h
  src/core/Entry.h
  src/core/EntryAttachments.h
  src/core/Group.h
  src/core/InactivityTimer.h
  src/gui/AboutDialog.h
  src/gui/ApplicationSettingsWidget.h
  src/gui/CategoryListWidget.h
  src/gui/CloneDialog.h
  src/gui/DatabaseOpenWidget.h
  src/gui/EditWidget.h
  src/gui/EditWidgetIcons.h
  src/gui/EditWidgetProperties.h
  src/gui/KMessageWidget.h
  src/gui/MainWindow.h
  src/gui/PasswordGeneratorWidget.h
  src/gui/TotpExportSettingsDialog.h
  src/gui/WelcomeWidget.h
  src/gui/csvImport/CsvImportWidget.h
  src/gui/csvImport/CsvParserModel.h
  src/gui/entry/EntryAttachmentsWidget.h
  src/gui/group/EditGroupWidget.h
  src/gui/osutils/OSUtilsBase.h
  src/gui/osutils/ScreenLockListener.h
  src/gui/reports/ReportsWidgetHibp.h
  src/gui/reports/ReportsWidgetStatistics.h
  src/gui/widgets/ElidedLabel.h
  src/streams/HashedBlockStream.h
  src/streams/HmacBlockStream.h
  src/streams/LayeredStream.h
  src/streams/SymmetricCipherStream.h
  src/streams/qtiocompressor.h
Labels: build system, refactor

#7869 clang-tidy: C++ headers
  src/core/Alloc.cpp
  src/gui/Application.cpp
  src/gui/styles/base/phantomcolor.cpp
Labels: build system, refactor

#7871 clang-tidy: use auto
  src/autotype/ShortcutWidget.cpp
  src/cli/AddGroup.cpp
  src/cli/Estimate.cpp
  src/core/Entry.cpp
  src/core/Group.cpp
  src/format/KeePass1Reader.cpp
  src/gui/Application.cpp
  src/gui/CategoryListWidget.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/KMessageWidget.cpp
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/SearchWidget.cpp
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/WelcomeWidget.cpp
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryAttachmentsWidget.cpp
  src/gui/entry/EntryModel.cpp
  src/gui/group/GroupModel.cpp
  src/gui/osutils/nixutils/ScreenLockListenerDBus.cpp
  src/gui/reports/ReportsPageStatistics.cpp
  src/gui/styles/base/BaseStyle.cpp
  src/gui/styles/base/phantomcolor.cpp
  src/streams/HashedBlockStream.cpp
  tests/TestDeletedObjects.cpp
  tests/TestEntry.cpp
  tests/TestEntryModel.cpp
  tests/TestEntrySearcher.cpp
  tests/TestGroup.cpp
  tests/TestGroupModel.cpp
  tests/TestHibp.cpp
  tests/TestMerge.cpp
Labels: build system, refactor

#7921 Add missing greater-than symbol in the password generator UI
  src/core/PasswordGenerator.cpp
  src/gui/PasswordGeneratorWidget.ui
Labels: user interface, backport-pending

#8021 FdoSecrets: skip entries in recycle bin when searching
  src/fdosecrets/objects/Collection.cpp
  src/fdosecrets/objects/Collection.h
  src/fdosecrets/objects/Service.cpp
  tests/gui/TestGuiFdoSecrets.cpp
  tests/gui/TestGuiFdoSecrets.h
Labels: feature: Secret Service, backport-pending

#8030 Move socket into separate directory
  src/browser/BrowserShared.cpp
Labels: platform: Linux, feature: Browser, backport-pending

#7748 Limit password entropy calculation using zxcvbn to 128 characters
  src/core/PasswordHealth.cpp
  src/core/PasswordHealth.h
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: bug, backport-pending

#8096 Fix transient errors in GUI tests
  tests/gui/TestGui.cpp
Labels: bug, tests, backport-pending
