Repository keepassxreboot/keepassxc, pull requests merged in 2023-10, with the labels that each got.

#9755 Change conf path XDG_CACHE_HOME to XDG_STATE_HOME
  docs/topics/DownloadInstall.adoc
  src/core/Config.cpp
Labels: platform: Linux

#9935 Create new UrlTools class
  src/CMakeLists.txt
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/core/Tools.cpp
  src/core/Tools.h
  src/core/UrlTools.cpp
  src/core/UrlTools.h
  src/gui/IconDownloader.cpp
  src/gui/URLEdit.cpp
  src/gui/entry/EntryURLModel.cpp
  tests/CMakeLists.txt
  tests/TestBrowser.cpp
  tests/TestBrowser.h
  tests/TestUrlTools.cpp
  tests/TestUrlTools.h
Labels: refactor

#9853 Fix raising Update Entry messagebox
  src/browser/BrowserService.cpp
Labels: bug, feature: Browser

#9747 Prevent scrollbars on entry drag/drop
  src/gui/entry/EntryView.cpp
Labels: bug, user interface

#8983 Add Polkit Quick Unlock mechanism
  .github/workflows/codeql.yml
  cmake/CLangFormat.cmake
  share/CMakeLists.txt
  share/linux/org.keepassxc.KeePassXC.policy.in
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/core/Database.cpp
  src/core/Database.h
  src/format/KdbxReader.cpp
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/DatabaseOpenWidget.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  src/gui/osutils/nixutils/NixUtils.cpp
  src/gui/osutils/nixutils/NixUtils.h
  src/gui/reports/ReportsDialog.cpp
  src/quickunlock/Polkit.cpp
  src/quickunlock/Polkit.h
  src/quickunlock/PolkitDbusTypes.cpp
  src/quickunlock/PolkitDbusTypes.h
  src/quickunlock/QuickUnlockInterface.cpp
  src/quickunlock/QuickUnlockInterface.h
  src/quickunlock/TouchID.h
  src/quickunlock/TouchID.mm
  src/quickunlock/WindowsHello.cpp
  src/quickunlock/WindowsHello.h
  src/quickunlock/dbus/org.freedesktop.PolicyKit1.Authority.xml
  src/touchid/TouchID.h
Labels: high priority :rotating_light:, security, platform: Linux, refactor, feature: QuickUnlock

#9939 Fix crash on database open from browser
  src/browser/BrowserService.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
Labels: bug, high priority :rotating_light:

#9822 Fix terminating KeePassXC processes with MSI installer
  share/windows/wix-template.xml
Labels: bug, distribution, platform: Windows

#9912 Do not hard-code colors in classic stylesheet for SearchBanner/KeeShareBanner
  src/gui/styles/base/classicstyle.qss
Labels: theme
