Repository keepassxreboot/keepassxc, pull requests merged in 2023-04, with the labels that each got.

#9138 Fix various accessibility issues
  share/translations/keepassxc_en.ts
  src/gui/EntryPreviewWidget.ui
  src/gui/MainWindow.cpp
  src/gui/PasswordWidget.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidgetMain.ui
Labels: bug, user interface, accessibility

#9205 Make open folder icon exempt from "Apply group icon to entry"
  src/core/Group.cpp
  src/core/Group.h
Labels: bug, user interface

#9230 Fix crash when search clears while creating new entry
  src/gui/EntryPreviewWidget.cpp
  src/gui/Icons.cpp
Labels: crash :boom:

#9192 Allow setting default file open directory with env var
  docs/topics/UserInterface.adoc
  src/gui/DatabaseWidget.cpp
  src/gui/FileDialog.cpp
  src/gui/FileDialog.h
Labels: ux
