Repository keepassxreboot/keepassxc, pull requests merged in 2023-02, with the labels that each got.

#7215 SSH Agent: Add support for generating SSH keys
  share/translations/keepassxc_en.ts
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EditEntryWidgetSSHAgent.ui
  src/sshagent/CMakeLists.txt
  src/sshagent/OpenSSHKey.cpp
  src/sshagent/OpenSSHKey.h
  src/sshagent/OpenSSHKeyGen.cpp
  src/sshagent/OpenSSHKeyGen.h
  src/sshagent/OpenSSHKeyGenDialog.cpp
  src/sshagent/OpenSSHKeyGenDialog.h
  src/sshagent/OpenSSHKeyGenDialog.ui
  tests/TestOpenSSHKey.cpp
  tests/TestSSHAgent.cpp
  tests/TestSSHAgent.h
Labels: new feature, feature: SSH agent

#9027 Fix wrong horizontal QR code resizing
  src/gui/SquareSvgWidget.cpp
  src/gui/SquareSvgWidget.h
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/TotpExportSettingsDialog.h
  tests/gui/TestGui.cpp
Labels: user interface, feature: TOTP

#9066 Autotype: fix text selection for clear_field step on Mac
  src/autotype/mac/AutoTypeMac.cpp
Labels: bug, feature: Auto-Type

#9073 Fix status bar update when switching to other DB
  src/gui/MainWindow.cpp
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: bug, user interface

#9101 Fix/database settings spin box bug
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.cpp
Labels: bug, user interface

#9096 Fix arrows size when expand/collapse a group
  src/gui/styles/base/BaseStyle.cpp
Labels: user interface

#9070 Select the clone instead of the original after cloning an entry
  src/gui/CloneDialog.cpp
  src/gui/CloneDialog.h
  src/gui/CloneDialog.ui
  src/gui/DatabaseWidget.cpp
  src/gui/entry/EntryModel.cpp
  src/gui/entry/EntryView.cpp
  tests/gui/TestGui.cpp
Labels: user interface

#9006 Fix crash when using Windows Hello in a Remote Desktop session
  share/translations/keepassxc_en.ts
  src/gui/DatabaseOpenWidget.cpp
  src/winhello/WindowsHello.cpp
Labels: crash :boom:, feature: QuickUnlock

#7790 revise strings labeling history limit settings
  share/translations/keepassxc_en.ts
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.ui
Labels: documentation :bookmark_tabs:

#8954 Translate Cipher and KDF strings
  share/translations/keepassxc_en.ts
  src/cli/DatabaseInfo.cpp
  src/format/KeePass2.cpp
  src/format/KeePass2.h
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
Labels: bug, i18n

#8489 Browser Integration code cleanup
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserMessageBuilder.cpp
  src/browser/BrowserMessageBuilder.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  tests/TestBrowser.cpp
  tests/TestBrowser.h
Labels: feature: Browser, refactor

#8994 Add optional support for Botan3
  CMakeLists.txt
  cmake/FindBotan3.cmake
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/browser/CMakeLists.txt
  src/config-keepassx.h.cmake
  src/crypto/Crypto.cpp
  src/fdosecrets/CMakeLists.txt
  src/fdosecrets/objects/SessionCipher.cpp
  src/keeshare/CMakeLists.txt
  src/proxy/CMakeLists.txt
Labels: build system

#8841 Add menu option to allow screenshots
  share/translations/keepassxc_en.ts
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/osutils/OSUtilsBase.cpp
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/winutils/WinUtils.cpp
  src/main.cpp
Labels: ux

#9137 Correct testing status bar text
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: cleanup

#9153 Turn search reset off by default
  src/core/Config.cpp
Labels: ux, feature: Search

#7292 Add 'get-database-entries' Proxy Request
  share/translations/keepassxc_en.ts
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserMessageBuilder.cpp
  src/browser/BrowserMessageBuilder.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/BrowserSettingsWidget.cpp
  src/browser/BrowserSettingsWidget.ui
  src/core/Config.cpp
  src/core/Config.h
Labels: new feature, feature: Browser

#9162 Fix TestGui::testDatabaseSettings open tab missing
  tests/gui/TestGui.cpp
Labels: tests

#9160 Make a direct reference to the Code of Conduct in the Contributing file.
  .github/CONTRIBUTING.md
Labels: documentation :bookmark_tabs:

#9136 Fix various bugs when returning credentials
  src/browser/BrowserAction.cpp
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, feature: Browser
