Repository keepassxreboot/keepassxc, pull requests merged in 2023-11, with the labels that each got.

#9984 Fix showing password generator from the toolbar icon
  src/gui/PasswordGeneratorWidget.cpp
Labels: bug

#9993 Fix docs link anchors
  src/gui/DatabaseOpenWidget.cpp
Labels: user interface, documentation :bookmark_tabs:

#9998 Passkeys: Rename User ID to Credential ID
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/passkeys/PasskeyExporter.cpp
  src/gui/passkeys/PasskeyImporter.cpp
  src/gui/passkeys/PasskeyImporter.h
Labels: bug, feature: Browser

#10044 Fix FindBotan.cmake: allow BOTAN_LIBRARY_DEBUG to be found in latest vcpkg
  cmake/FindBotan.cmake
Labels: build system

#9743 Fix password generator close button for good
  src/browser/BrowserAction.cpp
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/gui/PasswordGeneratorWidget.cpp
  src/gui/PasswordGeneratorWidget.h
Labels: feature: Browser, regression

#9987 Passkeys: Add support for importing Passkey to entry
  share/translations/keepassxc_en.ts
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/EntryAttributes.cpp
  src/core/EntryAttributes.h
  src/core/Tools.h
  src/format/OpVaultReaderBandEntry.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryURLModel.cpp
  src/gui/passkeys/PasskeyImportDialog.cpp
  src/gui/passkeys/PasskeyImportDialog.h
  src/gui/passkeys/PasskeyImportDialog.ui
  src/gui/passkeys/PasskeyImporter.cpp
  src/gui/passkeys/PasskeyImporter.h
  tests/TestBrowser.cpp
  tests/TestPasskeys.cpp
  tests/TestPasskeys.h
  tests/TestTools.cpp
  tests/TestTools.h
Labels: new feature, feature: PassKeys

#10039 Fix Botan 2/3 include
  src/keys/FileKey.h
Labels: cleanup
