Repository keepassxreboot/keepassxc, pull requests merged in 2023-05, with the labels that each got.

#9388 Fix Botan 3 build
  CMakeLists.txt
  COPYING
  cmake/FindBotan.cmake
  cmake/FindBotan2.cmake
  cmake/FindBotan3.cmake
  src/config-keepassx.h.cmake
  src/core/AsyncTask.h
  src/crypto/Crypto.cpp
  src/crypto/SymmetricCipher.cpp
  src/fdosecrets/objects/SessionCipher.cpp
Labels: build system

#9398 Greatly improve performance when rendering entry view
  src/core/Entry.cpp
  src/gui/SortFilterHideProxyModel.cpp
  src/gui/SortFilterHideProxyModel.h
  src/sshagent/KeeAgentSettings.cpp
Labels: bug, ux

#9380 Remove registry detection of desktop shortcut setting
  share/windows/wix-template.xml
Labels: distribution, platform: Windows, ux

#9382 Fix build failure with Qt5.6
  src/autotype/AutoTypeSelectDialog.cpp
Labels: Qt

#9383 use setWindowFlags() instead of setWindowFlag on Qt<5.9
  src/gui/CloneDialog.cpp
  src/gui/DatabaseOpenDialog.cpp
  src/gui/TotpSetupDialog.cpp
Labels: Qt
