Repository keepassxreboot/keepassxc, pull requests merged in 2024-03, with the labels that each got.

#10318 Passkeys improvements
  share/translations/keepassxc_en.ts
  src/browser/BrowserAction.cpp
  src/browser/BrowserAction.h
  src/browser/BrowserCbor.cpp
  src/browser/BrowserCbor.h
  src/browser/BrowserMessageBuilder.cpp
  src/browser/BrowserMessageBuilder.h
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  src/browser/BrowserPasskeysClient.cpp
  src/browser/BrowserPasskeysClient.h
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
  src/browser/BrowserSettings.cpp
  src/browser/BrowserSettings.h
  src/browser/BrowserSettingsWidget.cpp
  src/browser/BrowserSettingsWidget.ui
  src/browser/CMakeLists.txt
  src/browser/PasskeyUtils.cpp
  src/browser/PasskeyUtils.h
  src/core/Config.cpp
  src/core/Config.h
  src/core/Tools.cpp
  src/core/Tools.h
  src/core/UrlTools.cpp
  src/core/UrlTools.h
  src/gui/passkeys/PasskeyExporter.cpp
  tests/TestPasskeys.cpp
  tests/TestPasskeys.h
  tests/TestTools.cpp
  tests/TestTools.h
  tests/TestUrlTools.cpp
  tests/TestUrlTools.h
Labels: refactor, feature: PassKeys

#10088 Add vcpkg manifest with build dependencies
  .gitignore
  CMakeLists.txt
  INSTALL.md
  cmake/FindQREncode.cmake
  vcpkg-configuration.json
  vcpkg.json
  vcpkg/triplets/arm64-osx-dynamic-release.cmake
  vcpkg/triplets/arm64-osx-dynamic.cmake
  vcpkg/triplets/x64-osx-dynamic-release.cmake
  vcpkg/triplets/x64-osx-dynamic.cmake
Labels: build system

#10360 Skip a few Passkeys tests with Botan <= 2.14
  tests/TestPasskeys.cpp
  tests/TestPasskeys.h
Labels: bug, feature: PassKeys

#10266 Prevent byte-by-byte and attachment inference side channel attacks
  src/core/Database.cpp
  src/format/Kdbx4Writer.cpp
  src/format/Kdbx4Writer.h
  src/format/KdbxXmlWriter.cpp
  src/format/KdbxXmlWriter.h
  tests/TestKdbx3.cpp
  tests/TestKdbx3.h
  tests/TestKdbx4.cpp
  tests/TestKdbx4.h
Labels: security

#10466 Fix TestCli and TestGui entropy tests across platforms
  tests/TestCli.cpp
  tests/gui/TestGui.cpp
Labels: ci

#10397 Fix Indonesian language descriptor
  src/gui/AboutDialog.cpp
  utils/transifex_translators.py
Labels: user interface

#10459 Fix focusing search after database unlock
  src/gui/DatabaseOpenWidget.cpp
Labels: bug, feature: Search

#10500 Fix Message Box button size on Linux
  src/gui/DatabaseOpenWidget.cpp
  src/gui/MessageBox.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetEncryption.cpp
  src/gui/styles/base/basestyle.qss
Labels: bug, user interface, platform: Linux

#10343 Implemented database file hidden attribute preservation on Windows
  src/core/Database.cpp
  tests/TestDatabase.cpp
Labels: platform: Windows

#10282 Do not override fixed font size
  src/gui/Font.cpp
Labels: user interface

#10402 Passkeys: Allow nfc and usb transports
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  src/browser/PasskeyUtils.cpp
Labels: bug, feature: PassKeys

#10411 Passkeys: Add warning on export
  share/translations/keepassxc_en.ts
  src/gui/reports/ReportsWidgetPasskeys.cpp
Labels: ux, feature: PassKeys

#10420 Passkeys: Fix compatibility with StrongBox
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  src/browser/BrowserService.cpp
  src/browser/PasskeyUtils.cpp
  src/browser/PasskeyUtils.h
  src/gui/passkeys/PasskeyExporter.cpp
Labels: bug, feature: PassKeys

#10427 Passkeys: Enable Import Passkey entry menu item only if a single entry is selected
  src/gui/MainWindow.cpp
Labels: bug, feature: PassKeys

#10410 Passkeys: Do not ask update with a new user handle
  src/browser/BrowserService.cpp
  src/browser/BrowserService.h
Labels: bug, feature: PassKeys

#10384 Passkeys: Fix RP ID validation
  src/browser/BrowserService.cpp
  src/browser/PasskeyUtils.cpp
  tests/TestPasskeys.cpp
Labels: bug, feature: PassKeys

#10279 Remove various undefined/unused functions
  src/browser/BrowserService.h
  src/core/Group.h
  src/core/HibpDownloader.h
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EntryURLModel.h
  tests/TestCsvParser.h
Labels: cleanup
