Repository keepassxreboot/keepassxc, pull requests merged in 2024-08, with the labels that each got.

#11149 Bump GitHub workflow actions
  .github/workflows/codeql.yml
Labels: ci

#11082 Hardware keys: Fix PCSC daemon recovery on Linux
  src/keys/drivers/YubiKeyInterfacePCSC.cpp
Labels: bug, platform: Linux, feature: Hardware Keys

#11055 Browser: Resolve references in Access Confirm dialog
  src/browser/BrowserAccessControlDialog.cpp
Labels: bug, feature: Browser

#10966 Alternative impl for copy-to-clipboard shortcut
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug, platform: macOS

#9707 Add option to disable database lock when switching user on macOS
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetSecurity.ui
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/osutils/macutils/AppKit.h
  src/gui/osutils/macutils/AppKitImpl.mm
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
Labels: new feature, platform: macOS, feature: Browser

#11155 Prevent long-running threads from deadlocking the program with only 1 CPU
  src/main.cpp
Labels: bug, high priority :rotating_light:, regression

#9844 Use Icons for password strength
  COPYING
  share/icons/application/scalable/actions/lock-open-alert.svg
  share/icons/application/scalable/actions/lock-open.svg
  share/icons/application/scalable/actions/lock.svg
  share/icons/icons.qrc
  share/translations/keepassxc_en.ts
  src/gui/entry/EntryModel.cpp
  src/gui/reports/ReportsWidgetHealthcheck.cpp
Labels: user interface

#11192 CLI: Add `-d` dry-run shortcut to merge command
  src/cli/Merge.cpp
Labels: bug, feature: CLI

#11028 Windows: Fix icon not present on executable
  src/CMakeLists.txt
Labels: platform: Windows, build system, PRE-RELEASE BUG

#11099 Fix unexpected additional resolved urls in testIconDownloader
  tests/TestIconDownloader.cpp
Labels: tests

#11039 Fix signal/slot disconnect when opening import wizard
  src/gui/wizard/ImportWizardPageSelect.cpp
Labels: bug, high priority :rotating_light:, regression
