Repository keepassxreboot/keepassxc, pull requests merged in 2024-10, with the labels that each got.

#11271 Add possibility to configure timeout for remote process
  share/translations/keepassxc_en.ts
  src/gui/remote/DatabaseSettingsWidgetRemote.cpp
  src/gui/remote/DatabaseSettingsWidgetRemote.ui
  src/gui/remote/RemoteHandler.cpp
  src/gui/remote/RemoteSettings.cpp
  src/gui/remote/RemoteSettings.h
Labels: new feature, feature: Remote Sync

#10896 Support opening remote databases
  docs/topics/ImportExport.adoc
  share/translations/keepassxc_en.ts
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/wizard/ImportWizard.cpp
  src/gui/wizard/ImportWizard.h
  src/gui/wizard/ImportWizardPageReview.cpp
  src/gui/wizard/ImportWizardPageReview.h
  src/gui/wizard/ImportWizardPageSelect.cpp
  src/gui/wizard/ImportWizardPageSelect.h
  src/gui/wizard/ImportWizardPageSelect.ui
  tests/data/SyncDatabase.kdbx
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
Labels: new feature, feature: Remote Sync

#11047 Overhaul action states and add icons to toolbar
  COPYING
  share/icons/application/scalable/actions/database-settings.svg
  share/icons/application/scalable/actions/entry-delete.svg
  share/icons/application/scalable/actions/reports.svg
  share/icons/icons.qrc
  share/translations/keepassxc_en.ts
  src/fdosecrets/objects/Service.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/EditWidget.cpp
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/dbsettings/DatabaseSettingsDialog.cpp
  src/gui/reports/ReportsDialog.cpp
  src/gui/reports/ReportsDialog.h
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
  tests/gui/TestGuiBrowser.cpp
Labels: bug, user interface, ux

#11303 Fix horizontal scrollbar not showing in group view
  src/gui/group/GroupView.cpp
Labels: bug, user interface

#11306 Prevent multiple lock requests on Linux
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
Labels: bug, high priority :rotating_light:

#11154 Fix translations on Keyboard Shortcuts Widget
  share/translations/keepassxc_en.ts
  src/gui/ShortcutSettingsPage.cpp
Labels: i18n, PRE-RELEASE BUG

#10819 Add database name, color, and icon options for unlock view
  share/translations/keepassxc_en.ts
  src/core/Database.cpp
  src/core/Database.h
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.ui
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.h
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.ui
  src/gui/styles/base/basestyle.qss
  src/gui/styles/base/classicstyle.qss
Labels: user interface, new feature

#11332 Add option to disable opening a browser window when double-clicking the "URL" column in EntryView.cpp
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
Labels: user interface, new feature

#11273 Dark theme fix colors for qmenu
  src/gui/styles/dark/darkstyle.qss
Labels: user interface

#11351 Fix entry notes reveal button requiring two clicks sometimes
  src/gui/entry/EditEntryWidget.cpp
Labels: bug, user interface

#11367 Avoid hitting assert on XML export
  src/format/KdbxWriter.cpp
Labels: bug

#11373 Fix MacOS login items showing ambigious name
  src/gui/osutils/macutils/MacUtils.cpp
Labels: platform: macOS

#11360 Add SECURITY.md to guide security vulnerability reporting
  SECURITY.md
Labels: documentation :bookmark_tabs:

#11401 Support passkeys with Bitwarden import
  share/translations/keepassxc_en.ts
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  src/browser/BrowserService.cpp
  src/browser/PasskeyUtils.cpp
  src/core/EntryAttributes.cpp
  src/core/EntryAttributes.h
  src/format/BitwardenReader.cpp
  src/gui/passkeys/PasskeyExporter.cpp
  src/gui/passkeys/PasskeyImporter.cpp
  src/gui/reports/ReportsWidgetPasskeys.cpp
  tests/TestImports.cpp
  tests/TestImports.h
  tests/data/bitwarden_passkey_export.json
Labels: new feature, feature: Passkeys, import: Bitwarden

#11355 Hide the menubar when menus lose focus (if toggled off)
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
Labels: bug, user interface

#11413 Fix assert hit when viewing entry history
  src/gui/DatabaseWidget.cpp
  src/gui/EditWidget.cpp
  src/gui/EditWidget.h
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  tests/gui/TestGui.cpp
Labels: bug
