Repository keepassxreboot/keepassxc, pull requests merged in 2024-01, with the labels that each got.

#10138 ci: update checkout action
  .github/workflows/codeql.yml
Labels: ci

#10136 Fix database merge crash when fdosecrets is enabled
  src/core/Entry.cpp
  src/core/Merger.cpp
  src/core/Merger.h
  src/fdosecrets/objects/Collection.cpp
Labels: feature: Secret Service, crash :boom:

#10151 Passkeys: Fix default timeout on authentication
  src/browser/BrowserService.cpp
Labels: bug, PRE-RELEASE BUG, feature: PassKeys

#10087 Passkeys: Create AAGUID for KeePassXC
  src/browser/BrowserPasskeys.cpp
  src/browser/BrowserPasskeys.h
  tests/TestPasskeys.cpp
Labels: feature: PassKeys

#10059 Passkeys: UI adjustments
  share/translations/keepassxc_en.ts
  src/browser/BrowserPasskeysConfirmationDialog.cpp
  src/browser/BrowserPasskeysConfirmationDialog.h
  src/browser/BrowserPasskeysConfirmationDialog.ui
  src/browser/BrowserService.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetBrowser.cpp
  src/gui/passkeys/PasskeyExportDialog.ui
  src/gui/passkeys/PasskeyImportDialog.cpp
  src/gui/passkeys/PasskeyImportDialog.h
  src/gui/passkeys/PasskeyImportDialog.ui
Labels: feature: Browser, refactor, feature: PassKeys

#10054 Passkeys: Add Resident Key error
  share/translations/keepassxc_en.ts
  src/browser/BrowserMessageBuilder.cpp
  src/browser/BrowserMessageBuilder.h
  src/browser/BrowserService.cpp
Labels: bug, feature: Browser, feature: PassKeys

#9782 Add configurable password strength check on database password
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/gui/MessageBox.cpp
  src/gui/MessageBox.h
  src/gui/databasekey/PasswordEditWidget.cpp
  src/gui/databasekey/PasswordEditWidget.h
  src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
  tests/gui/TestGui.cpp
  tests/gui/TestGuiFdoSecrets.cpp
Labels: security, user interface, ux

#9874 Fix multiple TOTP issues
  src/CMakeLists.txt
  src/core/Entry.cpp
  src/core/Totp.cpp
  src/core/Totp.h
  src/format/OpVaultReaderSections.cpp
  src/gui/DatabaseWidget.cpp
  src/gui/EntryPreviewWidget.cpp
  src/gui/TotpDialog.cpp
  src/gui/TotpExportSettingsDialog.cpp
  src/gui/TotpSetupDialog.cpp
  src/gui/csvImport/CsvImportWidget.cpp
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  tests/TestCsvExporter.cpp
  tests/TestOpVaultReader.cpp
  tests/TestTotp.cpp
Labels: bug, feature: TOTP

#10075 Fix focus loss on save when the widget is not visible anymore
  src/gui/DatabaseWidget.cpp
Labels: bug, user interface

#9910 Fix QT-based system theme detection
  src/gui/osutils/nixutils/NixUtils.h
Labels: bug, theme

#9940 Fix logging for no clipping program worked
  src/cli/Utils.cpp
  tests/TestCli.cpp
Labels: feature: CLI

#9947 Fix issue about removing entry from history and improve logic of history tab showing
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EntryHistoryModel.cpp
Labels: bug, user interface

#10101 Fix Visual Studio install detection in release-tool.ps1
  release-tool.ps1
Labels: bug, build system, backported
