Repository keepassxreboot/keepassxc, pull requests merged in 2024-05, with the labels that each got.

#10408 Passkeys: Register to an existing entry
  share/translations/keepassxc_en.ts
  src/browser/BrowserMessageBuilder.cpp
  src/browser/BrowserPasskeysConfirmationDialog.cpp
  src/browser/BrowserService.cpp
  src/browser/BrowserSettingsWidget.ui
  src/gui/DatabaseWidget.cpp
  src/gui/passkeys/PasskeyExportDialog.ui
  src/gui/passkeys/PasskeyExporter.cpp
  src/gui/passkeys/PasskeyExporter.h
  src/gui/passkeys/PasskeyImportDialog.cpp
  src/gui/passkeys/PasskeyImportDialog.h
  src/gui/passkeys/PasskeyImportDialog.ui
  src/gui/passkeys/PasskeyImporter.cpp
  src/gui/passkeys/PasskeyImporter.h
  src/gui/reports/ReportsWidgetPasskeys.cpp
Labels: new feature, feature: PassKeys

#10642 Keep key file text when provided on command line
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
Labels: bug

#10663 Fix issues with Hardware Key auto detection
  src/gui/DatabaseOpenWidget.cpp
  src/gui/osutils/macutils/DeviceListenerMac.cpp
  src/keys/drivers/YubiKeyInterfaceUSB.cpp
Labels: bug, feature: Hardware Keys

#10687 Add keyutils package to snap build
  snap/snapcraft.yaml
Labels: distribution: Snap

#10650 Improve build time with MSVC
  CMakeLists.txt
Labels: platform: Windows, build system

#10795 Fix Alt modifier on Windows Auto-Type
  src/gui/osutils/winutils/WinUtils.cpp
Labels: bug, feature: Auto-Type

#10760 Improve Portability Check
  src/browser/NativeMessageInstaller.cpp
  src/core/Config.cpp
  src/core/Config.h
Labels: bug, feature: Browser

#10638 Fix SSH Agent broken decrypt button
  share/translations/keepassxc_en.ts
  src/gui/entry/EditEntryWidget.cpp
  src/sshagent/KeeAgentSettings.cpp
  src/sshagent/OpenSSHKey.cpp
Labels: bug, feature: SSH agent

#10688 Fix Flatpak config issues
  src/core/Config.cpp
  src/core/Config.h
  src/gui/osutils/nixutils/NixUtils.cpp
Labels: distribution: Flatpak

#10735 Prevent HTML overflow, fix #10647
  src/gui/HtmlExporter.cpp
Labels: bug, export: HTML

#10739 Restore macOS monospace font size prior to #10282
  src/gui/Font.cpp
Labels: user interface

#10717 Fix broken build when using system zxcvbn
  CMakeLists.txt
  COPYING
  cmake/CLangFormat.cmake
  codecov.yaml
  src/CMakeLists.txt
  src/cli/CMakeLists.txt
  src/thirdparty/zxcvbn/CMakeLists.txt
  src/thirdparty/zxcvbn/dict-src.h
  src/thirdparty/zxcvbn/zxcvbn.c
  src/thirdparty/zxcvbn/zxcvbn.h
  tests/CMakeLists.txt
  tests/TestCli.cpp
Labels: build system

#10777 Add action item for removing a passkey from entry
  share/translations/keepassxc_en.ts
  src/browser/BrowserSettingsWidget.ui
  src/core/Entry.cpp
  src/core/Entry.h
  src/core/EntryAttributes.cpp
  src/core/EntryAttributes.h
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseTabWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/SearchHelpWidget.ui
Labels: new feature, feature: PassKeys
