Repository keepassxreboot/keepassxc, pull requests merged in 2025-04, with the labels that each got.

#11994 Remove obsolete TLD test
  tests/TestUrlTools.cpp
Labels: pr: bugfix

#12005 Fix setting native messaging path with Tor Browser launcher in Linux
  src/browser/NativeMessageInstaller.cpp
Labels: platform: Linux, feature: Browser, pr: bugfix

#11919 Reduce tab indentation width in notes fields
  src/gui/EntryPreviewWidget.ui
  src/gui/entry/EditEntryWidgetMain.ui
Labels: user interface
