Repository keepassxreboot/keepassxc, pull requests merged in 2025-08, with the labels that each got.

#12370 Add more granular Auto-Type confirmation settings
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidget.h
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/DatabaseWidget.cpp
Labels: feature: Auto-Type, pr: ai-assisted

#12341 Add URL auto-type and copy options to auto-type selection popup and menus
  share/translations/keepassxc_en.ts
  src/autotype/AutoTypeSelectDialog.cpp
  src/autotype/AutoTypeSelectDialog.ui
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
Labels: feature: Auto-Type, pr: new feature, pr: ai-assisted

#12373 Documentation Updates Request #12359
  docs/UserGuide.adoc
  docs/images/browser_custom_browser_configuration.png
  docs/images/browser_integration_additional_attribute.png
  docs/images/browser_integration_clear_sites.png
  docs/images/browser_statistics.png
  docs/images/secretservice_access_dialog.png
  docs/images/secretservice_database_settings.png
  docs/images/secretservice_enable_settings.png
  docs/topics/BrowserIntegration.adoc
  docs/topics/SecretService.adoc
  docs/topics/UserInterface.adoc
Labels: documentation :bookmark_tabs:

#11839 Fix various typos
  cmake/FindPCSC.cmake
  docs/topics/DatabaseOperations.adoc
  share/translations/keepassxc_en.ts
  src/gui/Application.cpp
  src/gui/dbsettings/DatabaseSettingsWidgetGeneral.ui
  src/quickunlock/TouchID.mm
Labels: cleanup
