Repository keepassxreboot/keepassxc, pull requests merged in 2025-03, with the labels that each got.

#11950 Revert MSVC Redistributable Check
  share/windows/wix-template.xml
Labels: distribution, platform: Windows, regression

#11841 Write to buffer before writing directly to database file
  src/core/Database.cpp
Labels: high priority :rotating_light:, feature: Hardware Keys, pr: bugfix

#11874 Fix saving database backup file
  share/translations/keepassxc_en.ts
  src/gui/DatabaseWidget.cpp
Labels: pr: bugfix

#11963 implement database closing question on esc press
  share/translations/keepassxc_en.ts
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
Labels: ux
