Repository keepassxreboot/keepassxc, pull requests merged in 2025-06, with the labels that each got.

#12196 Fix loose URL comparison
  src/gui/UrlTools.cpp
  tests/TestUrlTools.cpp
Labels: feature: Browser, pr: bugfix

#12207 Add copilot management files
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
  README.md
Labels: build system

#11849 Maintain selected sort option when toggling filters
  src/gui/reports/ReportsWidgetHealthcheck.cpp
Labels: feature: Reports, pr: bugfix

#11888 Fix Proton Pass importer not importing email address when there is no username
  src/format/ProtonPassReader.cpp
Labels: pr: bugfix
