Repository keepassxreboot/keepassxc, pull requests merged in 2025-02, with the labels that each got.

#11650 Improve attachment handling by using a file watcher after you change …
  src/core/EntryAttachments.cpp
  src/gui/entry/NewEntryAttachmentsDialog.cpp
  src/gui/styles/dark/darkstyle.qss
  src/gui/styles/light/lightstyle.qss
Labels: pr: bugfix

#11703 Refactor YubiKey key to avoid deadlock
  src/keys/drivers/YubiKey.cpp
  src/keys/drivers/YubiKey.h
Labels: high priority :rotating_light:, feature: Hardware Keys, pr: bugfix

#10612 Fix issues with reloading and handling of externally modified db file
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/core/Database.cpp
  src/core/Database.h
  src/core/FileWatcher.cpp
  src/core/FileWatcher.h
  src/gui/DatabaseOpenDialog.cpp
  src/gui/DatabaseOpenDialog.h
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/streams/HashingStream.cpp
  src/streams/HashingStream.h
  tests/TestDatabase.cpp
  tests/TestDatabase.h
Labels: high priority :rotating_light:, pr: bugfix

#10091 Fix sorting of advanced attribute list
  src/gui/entry/EntryAttributesModel.cpp
  src/gui/entry/EntryAttributesModel.h
  tests/TestEntryModel.cpp
Labels: user interface

#10649 Implement function to clear all ssh-agent identities
  share/translations/keepassxc_en.ts
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/gui/MainWindow.ui
  src/gui/entry/EditEntryWidget.cpp
  src/gui/entry/EditEntryWidget.h
  src/gui/entry/EditEntryWidgetSSHAgent.ui
  src/sshagent/SSHAgent.cpp
  src/sshagent/SSHAgent.h
Labels: feature: SSH agent, pr: new feature

#11693 Add --minimized CLI option
  docs/man/keepassxc.1.adoc
  share/translations/keepassxc_en.ts
  src/main.cpp
Labels: pr: new feature

#11725 Show database public icon on tab when visible
  share/translations/keepassxc_en.ts
  src/core/Database.cpp
  src/gui/DatabaseTabWidget.cpp
  src/gui/DatabaseWidget.cpp
Labels: user interface

#11752 Prevent using URL wildcards in TLD
  src/gui/UrlTools.cpp
  tests/TestUrlTools.cpp
Labels: feature: Browser, PRE-RELEASE BUG, pr: bugfix

#11605 Prevent AltGr showing the menubar on Windows
  src/gui/MainWindow.cpp
Labels: user interface, platform: Windows, pr: bugfix

#11603 Show Auto-Type select dialog even if window title is empty
  src/autotype/AutoType.cpp
  src/autotype/AutoType.h
Labels: feature: Auto-Type, pr: bugfix

#11652 Support tearing off tags menu
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/styles/base/BaseStyle.cpp
Labels: feature: Tags, pr: new feature

#11590 Feature: HTML export from CLI tool
  share/translations/keepassxc_en.ts
  src/CMakeLists.txt
  src/cli/Export.cpp
  src/format/HtmlExporter.cpp
  src/format/HtmlExporter.h
  src/gui/HtmlGuiExporter.cpp
  src/gui/HtmlGuiExporter.h
  src/gui/export/ExportDialog.cpp
  tests/TestCli.cpp
Labels: feature: CLI, export: HTML

#11409 Clean up wordlist by removing hyphenated words and trailing newline
  share/wordlists/eff_large.wordlist
  tests/gui/TestGui.cpp
Labels: feature: Password Generator

#11785 Improve remote sync tests
  tests/gui/TestGui.cpp
  tests/gui/TestGui.h
  tests/mock/MockRemoteProcess.cpp
  tests/mock/MockRemoteProcess.h
Labels: pr: tests, cleanup
