Repository keepassxreboot/keepassxc, pull requests merged in 2025-01, with the labels that each got.

#11445 Minor style fixes
  src/gui/DatabaseWidget.cpp
  src/gui/styles/base/BaseStyle.cpp
  src/gui/styles/dark/darkstyle.qss
  src/gui/styles/light/lightstyle.qss
Labels: theme

#11609 Show a clear error if the key is found but the slots are not configured
  share/translations/keepassxc_en.ts
  src/gui/DatabaseOpenWidget.cpp
  src/gui/DatabaseOpenWidget.h
  src/gui/databasekey/YubiKeyEditWidget.cpp
  src/keys/drivers/YubiKey.cpp
  src/keys/drivers/YubiKey.h
  src/keys/drivers/YubiKeyInterface.h
  src/keys/drivers/YubiKeyInterfacePCSC.cpp
  src/keys/drivers/YubiKeyInterfacePCSC.h
  src/keys/drivers/YubiKeyInterfaceUSB.cpp
  src/keys/drivers/YubiKeyInterfaceUSB.h
  src/keys/drivers/YubiKeyStub.cpp
  tests/TestYkChallengeResponseKey.cpp
Labels: feature: Hardware Keys, ux

#11623 Implement Secure Input Mode on macOS
  src/gui/PasswordWidget.cpp
  src/gui/PasswordWidget.h
  src/gui/osutils/OSUtilsBase.h
  src/gui/osutils/macutils/MacUtils.cpp
  src/gui/osutils/macutils/MacUtils.h
  src/gui/osutils/nixutils/NixUtils.cpp
  src/gui/osutils/nixutils/NixUtils.h
  src/gui/osutils/winutils/WinUtils.cpp
  src/gui/osutils/winutils/WinUtils.h
Labels: high priority :rotating_light:, security, platform: macOS

#11625 Fix crash when pressing home key on empty tags field
  src/gui/tag/TagsEdit.cpp
Labels: crash :boom:, pr: bugfix

#11542 Fix setting window title as modified
  share/translations/keepassxc_en.ts
  src/gui/MainWindow.cpp
Labels: user interface, pr: bugfix

#8731 Implement #1972: Add ability to expire entries from context menus
  COPYING
  share/icons/application/scalable/actions/entry-expire.svg
  share/icons/icons.qrc
  share/translations/keepassxc_en.ts
  src/core/Entry.cpp
  src/core/Entry.h
  src/gui/DatabaseWidget.cpp
  src/gui/DatabaseWidget.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.ui
  src/gui/reports/ReportsWidgetBrowserStatistics.cpp
  src/gui/reports/ReportsWidgetBrowserStatistics.h
  src/gui/reports/ReportsWidgetHealthcheck.cpp
  src/gui/reports/ReportsWidgetHealthcheck.h
  src/gui/reports/ReportsWidgetHibp.cpp
  src/gui/reports/ReportsWidgetHibp.h
Labels: user interface, ux, pr: new feature

#11648 Add alternative path finding for PCSC headers/libraries
  cmake/FindPCSC.cmake
Labels: build system

#9417 Fix displaying escaped characters in message boxes
  src/gui/MessageBox.cpp
Labels: user interface, pr: bugfix

#9508 Remember sort order in Autotype popup dialog (WIP)
  src/autotype/AutoTypeSelectDialog.cpp
  src/core/Config.cpp
  src/core/Config.h
Labels: user interface, feature: Auto-Type, ux

#10278 "Group Full Path" column available in the EntryView
  share/translations/keepassxc_en.ts
  src/gui/entry/EntryModel.cpp
  src/gui/entry/EntryModel.h
  src/gui/entry/EntryView.cpp
Labels: user interface, pr: new feature

#11676 make tag-suggestions case insensitive
  src/gui/tag/TagsEdit.cpp
Labels: ux, feature: Tags

#11633 Trim file path settings fields prior to save
  src/browser/BrowserSettingsWidget.cpp
  src/sshagent/AgentSettingsWidget.cpp
Labels: pr: bugfix

#11567 Allow adjusting application font size
  share/translations/keepassxc_en.ts
  src/core/Config.cpp
  src/core/Config.h
  src/gui/Application.cpp
  src/gui/Application.h
  src/gui/ApplicationSettingsWidget.cpp
  src/gui/ApplicationSettingsWidgetGeneral.ui
  src/gui/Font.cpp
  src/gui/MainWindow.cpp
Labels: user interface, pr: new feature
